### PR TITLE
Switch to using explicit lists for callouts instead of crazy conditionals

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by plaindocs** [comment]
Nice. Thing is we then have to remember to update the CTAs as well as the Flags, which was the attraction of the CCs.

Any thoughts on how we can have the best of both worlds?

**Comment by plaindocs** [comment]
And we should include Vilnius if we're updating 2019 anything so we're on the same page.

**Comment by ericholscher** [comment]
> Any thoughts on how we can have the best of both worlds?

It just seems like there isn't actual state that we can capture here in a meaningful way. There's just too many times we want different things to be highlighted, depending on eg. sponsorship sales, ticket sales, etc. Seems like explicit is best here, so we can just make it say what we want when we want.

**Comment by ericholscher** [comment]
@plaindocs Updated Vilnius -- shall we merge and see how this goes, and we can move back towards conditionals if we don't like it?

**Comment by plaindocs** [comment]
Sure lets do it. 

Merging `master` will fix the build. 

We also have a PR open for Australia,  dunno if you wanna bother applying there also.

**Comment by ericholscher** [comment]
Yea, I want to do something similar to this for dates instead of `day_1`, because I think it will work much better in all cases. But baby steps :)

**Comment by plaindocs** [comment]
That's odd.

**Comment by plaindocs** [comment]
Why didn't the YAML linter pick up on that?

**Comment by plaindocs** [comment]
lol it did https://travis-ci.org/writethedocs/www/jobs/509400493

**Comment by ericholscher** [comment]
:+1:?

**Comment by plaindocs** [comment]
:ship::it:

**Review by plaindocs — APPROVED** [review]

**Pull request merged**
