### PR TITLE
Update staff pics Portland 2020

### PR DESCRIPTION
**Pull request by thatdocslady**

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
Would make sense to have them all lower case I think.

**Comment by mxsasha** [comment]
Fixing something, don't merge yet

**Comment by mxsasha** [comment]
I trimmed down the image sizes a bit, 4000x4000 images of 4 MB seemed a bit excessive - and this will be part of our git repo forever :)

**Comment by plaindocs** [comment]
We should set up https://github.com/marketplace/actions/image-optimizer  or something probably.

**Pull request merged**
