### PR TITLE
Add hoverxref extension for testing

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by humitos** [comment]
@ericholscher can you please re-trigger a build for this PR? The tooltip should display properly now. Let me know.

**Comment by humitos** [comment]
Example building locally:

Screenshot_2019-08-22_15-04-19

**Comment by humitos** [comment]
Just to note that there is nothing to change in this PR, new `master` branch in the extension has a small CSS fix for this.

**Comment by humitos** [comment]
Looks awesome!

**Comment by ericholscher** [comment]
Yea, I think we need to do some more additions around `:ref:`'s to make this really useful, we don't use them enough. It's an obvious win for using Sphinx directives over basic RST links tho 👍

**Comment by plaindocs** [comment]
If we hand picked a list of 20 pages or so that we think are "important" we could get a writing day task to convert them to directives.

**Pull request closed without merging**
