### PR TITLE
[WIP] Content fixes for the Prague 2018 site

### PR DESCRIPTION
**Pull request by thatdocslady**
WIP, do not review yet :) 

Many tweaks, new bios, updated variables, oh my!

------------

- [x] Add Media sponsor
- [x] Add first two Eu sponsors
- [x] Fix index/news
- [x] Fix index content

### CODE REVIEW

**Comment by thatdocslady** [comment]
Note to self: Do not merge until Sasha confirms volunteer coordinator role

**Comment by ericholscher** [comment]
We've gotten a few folks complaining about this on twitter/slack. Would be good to get some of the basic fixes out soon.

**Comment by ericholscher** [comment]
Ah, saw https://github.com/writethedocs/www/commit/761d63a9e53e4c52cb05cb9291ebeca15762d307 which I think fixes the worst of the issue.

**Comment by plaindocs** [comment]
Yep to both. I'll get this in tomorrow.

**Comment by plaindocs** [comment]
Almost done. 

Waiting on confirmation of EU sponsors. I'll fix up news/index and merge tomorrow.

**Comment by plaindocs** [comment]
@thatdocslady will you be writing the first news announcement?

**Pull request merged**
