### PR TITLE
Debug Futures

### PR DESCRIPTION
**Pull request by plaindocs**

### CODE REVIEW

**Comment by plaindocs** [comment]
:man_shrugging:

**Comment by mxsasha** [comment]
Do we actually need this though? From reading https://python-future.org/_modules/future/standard_library.html I don't see any imports that this affects. Maybe it was there for historic reasons?

**Comment by plaindocs** [comment]
I did wonder that. Futures is the Python 2 > 3 migration library right? And now we're running on 3 exclusively it should be safe to remove? 

Do you want to remove and push to this branch and see where we get?

**Comment by plaindocs** [comment]
Alternatatively merge this so we can update stuff and make another PR to remove future.

**Pull request merged**
