### PR TITLE
Use the codespell GH action

### PR DESCRIPTION
**Pull request by plaindocs**
As per a comment in #1608 this gives us annotations and coloured output.

### CODE REVIEW

**Comment by plaindocs** [comment]
hmmm, that didn't work

```
invalid value workflow reference: references to workflows must be rooted in '.github/workflows'
```

**Comment by mxsasha** [comment]
Maybe the indentation is off? Looking at the diff.

**Comment by plaindocs** [comment]
~I don't actually see a huge improvement~

image

**Comment by plaindocs** [comment]
@peternewman is this the expected output?

**Comment by mxsasha** [comment]
The annotation is visible in-line in Files Changed on https://github.com/writethedocs/www/pull/1621/files#diff-c22dc5bd8c63d1494b82f44acea240bc5f1016bf5657c0214ac1259964569863

**Comment by plaindocs** [comment]
Seems unintuitive to me to need to specify an image to run it on when the action is already defined, but that is nothing to do with this convo. @mxsasha approve if you're happy and we'll merge it in.

**Comment by peternewman** [comment]
You can also see all the annotations in the action runner:
https://github.com/writethedocs/www/actions/runs/1448663886

**Comment by plaindocs** [comment]
Ooh, @peternewman thank you once again, that is indeed nice

**Review by mxsasha — APPROVED** [review]
Thanks, this is a nice improvement :)

**Comment by peternewman** [comment]
> Seems unintuitive to me to need to specify an image to run it on when the action is already defined, but that is nothing to do with this convo. @mxsasha approve if you're happy and we'll merge it in.

It doesn't work with a default if not then? I've never really played and just copy-pasted working ones most of the time.

**Comment by plaindocs** [comment]
Yeah, it's a [required key](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on). I've not dug into whether you can specify it at the work-flow definition level not the repo you're using it in.

**Pull request merged**
