### PR TITLE
RTD updates

### PR DESCRIPTION
**Pull request by plaindocs**
----
📚 Documentation preview 📚: https://writethedocs-www--2240.org.readthedocs.build/

### CODE REVIEW

**Review by mxsasha — APPROVED** [review]

**Comment by plaindocs** [comment]
There is also config in the GH settings for that, so let's make sure that's the issue before committing ?

**Comment by mxsasha** [comment]
> There is also config in the GH settings for that, so let's make sure that's the issue before committing ?

Don't think it is on closer look. I think we're missing https:// prefix - trying that now. Might cause issues with PR builds and link checks though, as links won't be available on www.writethedocs.org and maybe there will be misdirected absolute URLs, that should have the PR URL instead. But I do want to get the recap out, so if this fixes that part, it'll have to do for now.

**Comment by plaindocs** [comment]
The content looks ok, so it *might* be just the linkchecker config

I'd rather disable that temporarily than revert the CI

**Comment by mxsasha** [comment]
> The content looks ok, so it _might_ be just the linkchecker config

Revert is already dropped, see other comment :)

**Pull request merged**
