### PR TITLE
Noodling on putting a nav back in

### PR DESCRIPTION
**Pull request by plaindocs**
I do not love how sphinx does nav.

----
:books: Documentation preview :books:: https://writethedocs-www--1971.org.readthedocs.build/

### CODE REVIEW

**Comment by plaindocs** [comment]
More consistent would be to just include the same toctree in site-map in the side bar.

```rst
.. toctree::
   :glob:
   :maxdepth: 2
   :titlesonly:
   :includehidden:

   about/events-activities
   about/learning-resources
   about/stay-connected
   about/about-the-org
```

image

But that distresses me by having the toctree in the index as well as the sidebar. 

or even 

```rst
.. toctree::
   :glob:
   :maxdepth: 1
   :titlesonly:
   :includehidden:

   about/events-activities
   about/learning-resources
   about/stay-connected
   about/about-the-org
```

But that's pretty sparse and probably not helpful:

image

**Comment by plaindocs** [comment]
The footer link containing the site map link doesn't display on mobile either. Non of this is very satisfactory.

**Comment by CollierCZ** [comment]
It seems like it would be possible to add a similar menu as is on the conference pages, it would just require UI Kit and all its JavaScript and CSS for all pages.

Alternatively, I can suggest how to make the footer visible on mobile pages with a CSS override.

**Comment by plaindocs** [comment]
@CollierCZ happy for you have a poke at this either way. I think a built in Nav would be better than the footer.

**Review by ericholscher — COMMENTED** [review]
This seems like a reasonable halfway solution. If we know what we actually want in the structure, I can also futz with it.

**Comment by CollierCZ** [comment]
For some reason, I read the comment about a built-in nav being better than a footer backwards, so built the footer. Can revert it and put in the nav if you like, just not today.

**Comment by CollierCZ** [comment]
Closes #1941

**Comment by CollierCZ** [comment]
Closes #1941
Closes #1931

**Review by plaindocs — COMMENTED** [review]
Site map in footer looks good on mobile. Shall we merge this, and you can add a nav back in another time?

@ericholscher @mxsasha one of you folks want to :+1: this, as it's technically my PR

**Comment by ericholscher** [comment]
Looking at the PR preview, it doesn't show anything in the content?

https://writethedocs-www--1971.org.readthedocs.build/

Screenshot 2023-08-03 at 10 49 30 AM

**Comment by plaindocs** [comment]
Good point, I looked at the footer. 

Maybe we can just revert https://github.com/writethedocs/www/pull/1971/commits/1673a065bfbf6ee7c0ac0654d8def472ed278509

**Comment by CollierCZ** [comment]
Oops. I'll fix that.

**Comment by plaindocs** [comment]
Could add something like 

```
+.. toctree::
+   :hidden:
+   :glob:
+   :maxdepth: 1
+
+   splunk-product-docs/*
```

to the end of `book-club/index.rst` to avoid these

**Comment by plaindocs** [comment]
@CollierCZ shall we merge this in? What do we need to do that?

**Comment by CollierCZ** [comment]
It's OK with me to merge, I think. Don't want to approve my own changes. 🤷

**Comment by plaindocs** [comment]
Right, I can't approve either, cos it's "my PR" :-p @mxsasha ?

**Review by mxsasha — APPROVED** [review]

**Comment by mxsasha** [comment]
> Right, I can't approve either, cos it's "my PR" :-p @mxsasha ?

I think in cases like this it's fine to press the loud red "bypass requirements" button.

**Pull request merged**
