### PR TITLE
Newsletter link checking

### PR DESCRIPTION
**Pull request by plaindocs**

### CODE REVIEW

**Comment by ericholscher** [comment]
Looks like this is already working since we're excluding old job postings already? 🎉 /cc @bethaitman

**Comment by plaindocs** [comment]
I KNOW RIGHT? :sun_with_face:

**Review by ericholscher — APPROVED** [review]

**Comment by ericholscher** [comment]
I imagine this will start randomly failing over  time as URL's we link to disappear, but that's good to know at least -- perhaps we can just point to archive.org copies when that happens.

**Comment by ericholscher** [comment]
🚢

**Pull request merged**
