### PR TITLE
Add CDC rec's to the Meetup COVID-19 notice

### PR DESCRIPTION
**Pull request by mjang**
From https://www.cdc.gov/coronavirus/2019-ncov/community/large-events/mass-gatherings-ready-for-covid-19.html

### CODE REVIEW

**Comment by mjang** [comment]
If y'all have typos or something similar, please feel free to pull this branch and merge the changes yourself.

(My availability will be limited for part of the day tomorrow.)

**Comment by thatdocslady** [comment]
Looks good Mike, the only thing I might suggest is to mention that for meetups outside the US they should follow the local laws and regulations. For example in CZ/IT/FR events are banned regardless of participants and everyone is quarantined, so any meetups must be virtual. I know most of our meetups are in the US, but for the sake of others (although I think the UK meetups would prefer the US model over what they have now, which is not much =/ )

**Comment by mjang** [comment]
> Looks good Mike, the only thing I might suggest is to mention that for meetups outside the US they should follow the local laws and regulations. For example in CZ/IT/FR events are banned regardless of participants and everyone is quarantined, so any meetups must be virtual. I know most of our meetups are in the US, but for the sake of others (although I think the UK meetups would prefer the US model over what they have now, which is not much =/ )

I've added:

```
Many Countries Have Temporarirly Banned All "In-Person" Meetups
===============================================================

Be sure to follow the laws, regulations, and recommendations of the health authorities in your area.
```

**Comment by thatdocslady** [comment]
Great Mike, LGTM

**Review by thatdocslady — APPROVED** [review]

**Review by mxsasha — APPROVED** [review]
Yes, it's good to add a mention for non-US meetups too. Looks good!

**Comment by mjang** [comment]
Given the situation, I'm proceeding with a merge.

**Review by meker12 — COMMENTED** [review]
LGTM +1 OK to merge.

**Pull request merged**
