### PR TITLE
Static templates for Write the docs conferences and meetup videos 

### PR DESCRIPTION
**Pull request by xpostudio4**
I created templates to display both videos and the individual conferences videos and the meetups.

The relative urls to access the templates are:
/conf/na/2017/videos/
/conf/na/2017/conference-videos/
/conf/na/2017/individual-meetup/
/conf/na/2017/video-detail/

Here I attach the original images for the views as well as the original sketch if anyone needs reference for the proposal. If anything needs to be changed
[Write the Docs.zip](https://github.com/writethedocs/www/files/1023966/Write.the.Docs.zip)

 just let me know.

individual video view
meetups individual view
meetups view index
conference views index

### CODE REVIEW

**Comment by ericholscher** [comment]
Thanks again @xpostudio4! I'll take a look at this in the next couple days and get it templated out.

**Comment by plaindocs** [comment]
Yeah, this looks AMAZING! Once @ericholscher has templated it out, and @zerok has fixed up the yaml datasources it should be pretty easy for me to merge this in and start populating it.

Exciting times!

**Comment by plaindocs** [comment]
Ping @ericholscher

**Comment by ericholscher** [comment]
Don't really have time to work on this until after Prague, probably.

**Comment by zerok** [comment]
@xpostudio4 Awesome, thank you so much! I will try to convert these now into as many static pages as possible using the data we have :)

**Pull request merged**
