### PR TITLE
Fixes issues on Issue #367

### PR DESCRIPTION
**Pull request by xpostudio4**

### CODE REVIEW

**Comment by plaindocs** [comment]
In mobile (chrome) if the WTD logo looks blue:
photo5830458387274509022

**Comment by plaindocs** [comment]
Otherwise thanks a ton for these fixes! :-)

**Comment by xpostudio4** [comment]
@plaindocs, I'm not able to reproduce it
screen shot 2017-11-28 at 11 51 28 am

**Comment by plaindocs** [comment]
Your pic is from a desktop, no? I'm talking about mobile.

**Comment by thatdocslady** [comment]
Superceded by PR #377

**Pull request merged**
