### PR TITLE
CrispyCB FAQ

### PR DESCRIPTION
**Pull request by CrispyCB**
Added my "New Interview FAQ" markdown file to the guide page. @Bradamant3 @msemp

### CODE REVIEW

**Comment by Bradamant3** [comment]
hey @CrispyCB it looks as though bc your earlier PR was from your master, you've got its commit in this PR also. Can you clean up, please? Thanks! (best practice always to work from a branch in your fork, not from master, although it looks as though you've probably already figured that one out)

**Comment by plaindocs** [comment]
Yes indeed, you have the old commit from #386 which still needs switching out to the correct year. :-)

**Comment by CrispyCB** [comment]
I see that. How do I fix it? The Github guides I've found online haven't been very helpful.

**Comment by Bradamant3** [comment]
@CrispyCB If you fix up your earlier commit (move it to the location requested in the comment), then one of the owners/maintainers can merge your PR. Then you can update your master (make sure it's up to date with upstream), update this commit if needed, and this PR should be clean.

**Comment by ericholscher** [comment]
Just wanted to ping this PR. Seems like it just needs a bit of cleanup in order to merge, and I'd love to see it in the guide!

**Comment by ericholscher** [comment]
Seems like it just needs the file to be renamed, and then we're good to go?

**Comment by ghost** [comment]
Sorry; it's been on my ToDo list. I've a number of Write the Docs-oriented things, which I can make sure to take care of next week (week of Mar. 19, 2018). I'm planning to make a few editorial/style suggestions, with the expectation that @CrispyCB will be up for making a few updates. And then I can approve things.

**Comment by plaindocs** [comment]
Closing this, please feel free to reopen.

**Pull request closed without merging**
