### PR TITLE
Update schedule YAML

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by plaindocs** [comment]
THANKS!

**Comment by thatdocslady** [comment]
Yay! Can I merge this already? @plaindocs did you make the swap changes, I can't remember what we had...

**Comment by plaindocs** [comment]
No merging @thatdocslady !

**Comment by plaindocs** [comment]
I've made speaker updates. 

@ericholscher did we entirely give up on linking to sessions when we started using data templates?

**Comment by plaindocs** [comment]
Not any more we didn't. 

Can we get a nice clean sphinx setup someday?

**Comment by plaindocs** [comment]
@thatdocslady fire at will!

**Pull request merged**
