### PR TITLE
vale changes install again

### PR DESCRIPTION
**Pull request by plaindocs**
Should fix the latest broken builds.

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
Annoying :/

**Comment by jdkato** [comment]
Sorry about that -- I have made some installation changes for v2.0.0, but my intent was to *avoid* breaking the existing methods. I believe I've fixed the issue now, though, so the old `go get` method should be working again.

**Comment by plaindocs** [comment]
Hahah, @jdkato that is even worse now I've update the build! ;-) Especially when your docs don't reference the `go get` as an official method.

**Comment by jdkato** [comment]
It isn't an "official method" and hasn't been for almost a year (I changed this shortly after v1.0.0 was released) because of the inability to install a certain version (it's always simply `master` with `go get`), but I still try to avoid breaking existing installations when I make changes.

Again, sorry for the inconvenience.

**Pull request merged**
