### PR TITLE
CFP, Venue and other details

### PR DESCRIPTION
**Pull request by swapnilogale**

### CODE REVIEW

**Comment by swapnilogale** [comment]
@plaindocs - I tried putting these together, but can't figure out why the CFP page won't link correctly and display AU content.

**Comment by ericholscher** [comment]
Seems like it's working to me @swapnilogale? https://deploy-preview-964--dentist-canary-64055.netlify.com/conf/australia/2019/cfp/ has your content.

**Comment by swapnilogale** [comment]
@ericholscher thanks. Must have been a browser issue, looks fine to me now. I still need to turn on the Google forms and ticketing, so I'll check on this tonight.

**Comment by swapnilogale** [comment]
@plaindocs @ericholscher added some more info on team, venue, CFP and it looks ok. Have also turned on CFP form and can make the tickets live to test this out. Thoughts?

**Comment by swapnilogale** [comment]
The Travis/CI build seems to be failing and also, for some reason, I can't get any space between the buttons and the next section on the home page

**Comment by swapnilogale** [comment]
@plaindocs could you review this (and recommend changes, if any)? Planning to go live with CFP, tickets and sponsorships by 15th June.

**Comment by plaindocs** [comment]
Will do, probably take me a couple of days

**Comment by plaindocs** [comment]
@swapnilogale you've introduced a ton of broken links to pages that don't exist:

```
- /home/travis/build/writethedocs/www/.tox/links/tmp/html/conf/australia/2019/cfp/index.html
  *  internally linking to ../prospectus/, which does not exist (line 133)
     <a href="../prospectus/">Prospectus</a>
  *  internally linking to ../workshop-ssg/, which does not exist (line 106)
     <a href="../workshop-ssg/">Static Site Generators Workshop</a>
  *  internally linking to ../workshop-style-guide/, which does not exist (line 105)
     <a href="../workshop-style-guide/">Style Guide Workshop</a>
  *  internally linking to ../workshop-tech-writing/, which does not exist (line 104)
     <a href="../workshop-tech-writing/">Tech Writing Workshop</a>
```

What about adding a single `workshops` page, with the 3 headings, and putting TBA in each one?

**Comment by swapnilogale** [comment]
@plaindocs ok. I'll fix this tomorrow.

**Comment by plaindocs** [comment]
There is also an odd broken link related to `../prospectus` which I'm having trouble tracking down

**Review by plaindocs — APPROVED** [review]
I think this is good to go, but if any other @writethedocs/core want to take a look before @swapnilogale merges this in, now would be the time.

**Comment by ericholscher** [comment]
I gave it a peek already, so assuming nothing broke since then, I'm 👍

**Pull request merged**
