### PR TITLE
Create code-of-conduct-shortform-meetups.rst

### PR DESCRIPTION
**Pull request by AWS-SF**
Created in response to https://github.com/writethedocs/www/issues/71 and discussion at WriteTheDocsDay Portland 2018 of how this might be useful for meetup welcoming slides.

### CODE REVIEW

**Comment by AWS-SF** [comment]
Per discussion, attention to @ericholscher @mjang @plaindocs for review

**Comment by mjang** [comment]
Question -- where would you link to this file?

**Comment by AWS-SF** [comment]
@mjang - Not sure I understand the context correctly. Are you asking where this file should live in the repo structure? I'd keep it in the same directory as the full CoC. If you're asking where this might live on the WritetheDocs website, I'd reference it from http://www.writethedocs.org/organizer-guide/meetups/starting/ and the conferences page. I didn't see a "here's a bunch of resources you can use when putting together a meetup or a conference" page, but that's something that might be helpful.

**Review by rosewms — APPROVED** [review]
Looks good, I appreciate the summary, should fit well on a slide for event decks.

**Comment by mjang** [comment]
@AWS-SF Your answer makes sense. Keep it in the same directory as the CoC.

**Comment by mjang** [comment]
Merging this PR. Will set up a link from the "Minimal Viable Meetup checklist" in a separate PR.

**Pull request merged**
