### PR TITLE
Finished list, per your request

### PR DESCRIPTION
**Pull request by nikblanchet**
I scoured Twitter and Google looking for write-ups, and I found the
following.

### CODE REVIEW

**Comment by plaindocs** [comment]
You are off brand my friend. ;-)

**Comment by plaindocs** [comment]
this is greaT!

**Comment by nikblanchet** [comment]
BTW, in online profiles, when people capitalize the T in the word parTy, they are indicating that they want to use meth (chemsex). (One slang term for meth is Tina.) Because the various site owners don't want to be accused of encouraging this behavior, they have bots that now block user profiles that capitalize parTy that way. In response, users have just started using capital Ts in other words to get their point across. What I'm trying to say is: Thanks for merging my pull request, but no, I won't do meth with you.

**Comment by plaindocs** [comment]
I like your work but I don't approve of your meThods.

**Pull request merged**
