### PR TITLE
Updated speakers and schedule pages

### PR DESCRIPTION
**Pull request by swapnilogale**
Added speaker bios, presentations and schedule. 
Also added speaker images for everyone (except Russell)

### CODE REVIEW

**Comment by plaindocs** [comment]
Meh, this is still kinda broken - but one can at least view the text - kinda. 

... investigating ...

**Comment by plaindocs** [comment]
@swapnilogale take a look at this and see what you think.

**Comment by swapnilogale** [comment]
Happy with these changes at the moment. Will raise another PR for other fixes tomorrow.

**Comment by plaindocs** [comment]
I've fixed the anchors, you probably want to update the date for the first news entry.

**Pull request merged**
