### PR TITLE
Creating a new file for bingo cards

### PR DESCRIPTION
**Pull request by runleonarun**
Is this an ok way to capture this? If not, no worries. Thanks, Eric!

### CODE REVIEW

**Comment by plaindocs** [comment]
Hi @runleonarun how do we get the cards into the printable template? 

This is fine, don't even really need the line numbers. 
It *might* be easier in a google spreadsheet? 

Anyway, I can merge this whenever you like, or let me know if you need anything else.

**Comment by runleonarun** [comment]
@ericholscher @plaindocs I think you had put the in the template last year, but I am happy to do it if you pass the template along to me. I couldn't find it anywhere.

**Comment by ericholscher** [comment]
We used this script to do it last year, we should be able to have it load from a CSV or other kind of file, and generate the cards again this year. I can probably handle that are a pre-production step: https://github.com/writethedocs/resources/blob/master/conf/2016/generate-bingo.py

**Comment by runleonarun** [comment]
Or should I just edit the script directly? Happy to do that if it makes it easier.

**Comment by plaindocs** [comment]
What I'd suggest is @runleonarun close this PR, and open another adding the content to the script.

Eric / myself should move the script out of the conf, and have it pick up a CSV file from each conf location / year instead.

The python script is a 2.x not 3.x and does not work out of the box for me.

test

**Comment by thatdocslady** [comment]
@runleonarun @plaindocs I suggest that anything to do with print assets should be handled in the resources repo: https://github.com/writethedocs/resources and that the relevant files be checked into the correct location in the repo: https://github.com/writethedocs/resources/tree/master/conf/2017/na

**Comment by ericholscher** [comment]
Pushed this change to the resources repo. Closing this :+1:

**Pull request closed without merging**
