### PR TITLE
Adding Style Guide content

### PR DESCRIPTION
**Pull request by db4rr**
First version of the style guide chapter authored during the Write the Docs Prague 2017 writing day

### CODE REVIEW

**Comment by plaindocs** [comment]
Can I suggest renaming this PR? To something like Adding a Style Guide? 

Looks like awesome stuff though!

**Comment by db4rr** [comment]
If you guys prefer a more task-oriented approach in your doc guide, how about "Choosing a style guide"? You don't really "add" the style guide :)

**Comment by plaindocs** [comment]
I'm just talking about the Pull Request, not the documents themselves.

**Comment by db4rr** [comment]
Right! I missed that, didn't realise we left that blank --- done!

**Comment by codeharmonics** [comment]
Please close this PR, it is outdated, replaced by https://github.com/writethedocs/www/pull/292

**Review by codeharmonics — COMMENTED** [review]
Replaced by https://github.com/writethedocs/www/pull/292

**Pull request closed without merging**
