### PR TITLE
YAML conversion fixes

### PR DESCRIPTION
**Pull request by zerok**

### CODE REVIEW

**Comment by plaindocs** [comment]
mmm, this still doesn't fix the build issue for me. :/

**Comment by zerok** [comment]
The same error message or something new? What version of docutils do you have in your virtual env?

**Comment by plaindocs** [comment]
This is what RTD tells me is going on
```
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging
python /home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/.cache/pip sphinx==1.5.3 Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext<0.6 sphinx-rtd-theme<0.3 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0
python /home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/checkouts/staging/requirements.txt
cat docs/conf.py
python /home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/
```

**Comment by plaindocs** [comment]
And full error log:

```
Running Sphinx v1.4.9
making output directory...
initializing sphinxcontrib.datatemplates
loading translations [en]... done
WARNING: The config value `fontawesome_link_cdn' has type `str', defaults to `bool.'
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [json]: targets for 185 source files that are out of date
updating environment: 185 added, 0 changed, 0 removed
reading sources... [  0%] blog/index
reading sources... [  1%] blog/new-community-coc
reading sources... [  1%] blog/newsletter-april-2017
reading sources... [  2%] blog/newsletter-december-2016
reading sources... [  2%] blog/newsletter-february-2017
reading sources... [  3%] blog/newsletter-march-2017
reading sources... [  3%] blog/newsletter-may-2017
reading sources... [  4%] blog/newsletter-november-2016
reading sources... [  4%] blog/newsletter-october-2016
reading sources... [  5%] blog/newsletter-september-2016
reading sources... [  5%] blog/team-eu-speakers
reading sources... [  6%] blog/welcome
reading sources... [  7%] blog/write-the-docs-2016-year-in-review
reading sources... [  7%] code-of-conduct
reading sources... [  8%] code-of-conduct-reporting
reading sources... [  8%] code-of-conduct-response
reading sources... [  9%] conf/eu/2015/cfp
reading sources... [  9%] conf/eu/2015/index
reading sources... [ 10%] conf/eu/2015/lightning-talks
reading sources... [ 10%] conf/eu/2015/news/announcing-eu-2015
reading sources... [ 11%] conf/eu/2015/news/announcing-eu-events-sponsors-tickets
reading sources... [ 11%] conf/eu/2015/news/announcing-eu-parties-sponsors
reading sources... [ 12%] conf/eu/2015/news/announcing-eu-presentations
reading sources... [ 12%] conf/eu/2015/news/announcing-eu-tickets
reading sources... [ 13%] conf/eu/2015/news/announcing-reception-weather-tickets
reading sources... [ 14%] conf/eu/2015/news/eu-early-tickets-videos-cfp
reading sources... [ 14%] conf/eu/2015/news/eu-thanks-for-coming
reading sources... [ 15%] conf/eu/2015/news/pre-conf-info
reading sources... [ 15%] conf/eu/2015/schedule
reading sources... [ 16%] conf/eu/2015/speakers
reading sources... [ 16%] conf/eu/2015/visiting
reading sources... [ 17%] conf/eu/2016/cfp
reading sources... [ 17%] conf/eu/2016/index
reading sources... [ 18%] conf/eu/2016/lightning-talks
reading sources... [ 18%] conf/eu/2016/news/announce-presentations
reading sources... [ 19%] conf/eu/2016/news/cfp-new-deadline
reading sources... [ 20%] conf/eu/2016/news/cfp-tickets
reading sources... [ 20%] conf/eu/2016/news/code-of-conduct-report
reading sources... [ 21%] conf/eu/2016/news/day-of
reading sources... [ 21%] conf/eu/2016/news/schedule
reading sources... [ 22%] conf/eu/2016/news/thanks-for-coming
reading sources... [ 22%] conf/eu/2016/news/videos-coc-report
reading sources... [ 23%] conf/eu/2016/news/welcome
reading sources... [ 23%] conf/eu/2016/schedule
reading sources... [ 24%] conf/eu/2016/speakers
reading sources... [ 24%] conf/eu/2016/unconference
reading sources... [ 25%] conf/eu/2016/visiting
reading sources... [ 25%] conf/eu/2016/writingday
reading sources... [ 26%] conf/eu/2017/about
reading sources... [ 27%] conf/eu/2017/boat
reading sources... [ 27%] conf/eu/2017/cfp
reading sources... [ 28%] conf/eu/2017/index
reading sources... [ 28%] conf/eu/2017/lightning-talks
reading sources... [ 29%] conf/eu/2017/news/announcing-cfp
reading sources... [ 29%] conf/eu/2017/news/announcing-website-tickets
reading sources... [ 30%] conf/eu/2017/news/cfp-reminder
reading sources... [ 30%] conf/eu/2017/news/index
reading sources... [ 31%] conf/eu/2017/schedule
WARNING: The builder has no template manager, ignoring the datatemplate directive.
WARNING: The builder has no template manager, ignoring the datatemplate directive.
WARNING: The builder has no template manager, ignoring the datatemplate directive.
reading sources... [ 31%] conf/eu/2017/speakers
reading sources... [ 32%] conf/eu/2017/sponsor
reading sources... [ 32%] conf/eu/2017/sponsorship/prospectus
reading sources... [ 33%] conf/eu/2017/staff
reading sources... [ 34%] conf/eu/2017/tickets
reading sources... [ 34%] conf/eu/2017/unconference
reading sources... [ 35%] conf/eu/2017/venue
reading sources... [ 35%] conf/eu/2017/visiting
reading sources... [ 36%] conf/eu/2017/welcome-wagon
reading sources... [ 36%] conf/eu/2017/writing-day
WARNING: The builder has no template manager, ignoring the datatemplate directive.
reading sources... [ 37%] conf/index
reading sources... [ 37%] conf/na/2015/cfp
reading sources... [ 38%] conf/na/2015/hike
reading sources... [ 38%] conf/na/2015/index
reading sources... [ 39%] conf/na/2015/lightning-talks
reading sources... [ 40%] conf/na/2015/news/announcing-2015
reading sources... [ 40%] conf/na/2015/news/announcing-keynotes-sponsors-reminder
reading sources... [ 41%] conf/na/2015/news/announcing-presentations
reading sources... [ 41%] conf/na/2015/news/cfp-ticket-prices
reading sources... [ 42%] conf/na/2015/news/conference-sold-out-schedule-party
reading sources... [ 42%] conf/na/2015/news/more-conference-details
reading sources... [ 43%] conf/na/2015/news/thanks-for-coming
reading sources... [ 43%] conf/na/2015/news/videos-forum-eu-cfp
reading sources... [ 44%] conf/na/2015/news/welcome-to-write-the-docs
reading sources... [ 44%] conf/na/2015/schedule
reading sources... [ 45%] conf/na/2015/speakers
reading sources... [ 45%] conf/na/2015/visiting
reading sources... [ 46%] conf/na/2015/writing-day
reading sources... [ 47%] conf/na/2016/cfp
reading sources... [ 47%] conf/na/2016/hike
reading sources... [ 48%] conf/na/2016/index
reading sources... [ 48%] conf/na/2016/lightning-talks
reading sources... [ 49%] conf/na/2016/news/announcing-2016
/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/recommonmark/parser.py:280: UserWarning: Unsupported inline type Hardbreak
  warn("Unsupported inline type " + inline.t)
reading sources... [ 49%] conf/na/2016/news/announcing-presentations
reading sources... [ 50%] conf/na/2016/news/cfp-reminder
reading sources... [ 50%] conf/na/2016/news/cfp-tickets
reading sources... [ 51%] conf/na/2016/news/schedule-welcome-wagon-events
reading sources... [ 51%] conf/na/2016/news/thanks-for-coming
reading sources... [ 52%] conf/na/2016/news/welcome
reading sources... [ 52%] conf/na/2016/schedule
reading sources... [ 53%] conf/na/2016/speakers
reading sources... [ 54%] conf/na/2016/unconference
reading sources... [ 54%] conf/na/2016/venue
reading sources... [ 55%] conf/na/2016/visiting
reading sources... [ 55%] conf/na/2016/welcome-wagon
reading sources... [ 56%] conf/na/2016/writing-day
reading sources... [ 56%] conf/na/2017/about
reading sources... [ 57%] conf/na/2017/cfp
reading sources... [ 57%] conf/na/2017/east/proposal
reading sources... [ 58%] conf/na/2017/hike
reading sources... [ 58%] conf/na/2017/index
reading sources... [ 59%] conf/na/2017/lightning-talks
reading sources... [ 60%] conf/na/2017/news/announcing-presentations
reading sources... [ 60%] conf/na/2017/news/announcing-tickets-cfp-website
reading sources... [ 61%] conf/na/2017/news/announcing-workshops
reading sources... [ 61%] conf/na/2017/news/cfp-reminder
reading sources... [ 62%] conf/na/2017/news/index
reading sources... [ 62%] conf/na/2017/news/schedule-social
reading sources... [ 63%] conf/na/2017/news/thanks-for-coming
reading sources... [ 63%] conf/na/2017/news/welcome
reading sources... [ 64%] conf/na/2017/schedule
WARNING: The builder has no template manager, ignoring the datatemplate directive.
WARNING: The builder has no template manager, ignoring the datatemplate directive.
WARNING: The builder has no template manager, ignoring the datatemplate directive.
WARNING: The builder has no template manager, ignoring the datatemplate directive.
reading sources... [ 64%] conf/na/2017/speakers
reading sources... [ 65%] conf/na/2017/sponsor
reading sources... [ 65%] conf/na/2017/sponsorship/prospectus
reading sources... [ 66%] conf/na/2017/team
reading sources... [ 67%] conf/na/2017/tickets
reading sources... [ 67%] conf/na/2017/unconference
reading sources... [ 68%] conf/na/2017/venue
reading sources... [ 68%] conf/na/2017/visiting
reading sources... [ 69%] conf/na/2017/welcome-wagon
reading sources... [ 69%] conf/na/2017/workshops
WARNING: The builder has no template manager, ignoring the datatemplate directive.
reading sources... [ 70%] conf/na/2017/writing-day
WARNING: The builder has no template manager, ignoring the datatemplate directive.
reading sources... [ 70%] conf/na/shirts/index
reading sources... [ 71%] conf/speaking
reading sources... [ 71%] conf/sponsorship/prospectus
reading sources... [ 72%] conf/unconference
reading sources... [ 72%] documentarians
reading sources... [ 73%] guide/about/alternatives
reading sources... [ 74%] guide/about/community
reading sources... [ 74%] guide/about/index
reading sources... [ 75%] guide/about/vision
reading sources... [ 75%] guide/api/about-api-documentation
reading sources... [ 76%] guide/api/apiary
reading sources... [ 76%] guide/api/apiblueprint
reading sources... [ 77%] guide/api/generating-documents
reading sources... [ 77%] guide/api/languages
reading sources... [ 78%] guide/api/testing
reading sources... [ 78%] guide/contributing
reading sources... [ 79%] guide/docs-as-code
reading sources... [ 80%] guide/index
reading sources... [ 80%] guide/presentations/index
reading sources... [ 81%] guide/starting
reading sources... [ 81%] guide/tools/index
reading sources... [ 82%] guide/tools/sphinx
reading sources... [ 82%] guide/tools/sphinx-themes
reading sources... [ 83%] guide/tools/testing
reading sources... [ 83%] guide/writing/beginners-guide-to-docs
reading sources... [ 84%] guide/writing/docs-principles
reading sources... [ 84%] guide/writing/mindshare
reading sources... [ 85%] guide/writing/oss
reading sources... [ 85%] index
reading sources... [ 86%] meetups/index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/environment.py", line 569, in update
    self._read_serial(docnames, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/environment.py", line 589, in _read_serial
    self.read_doc(docname, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/environment.py", line 742, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2129, in run_directive
    'Directive "%s" must return a list of nodes.' % type_name
AssertionError: Directive "meetup-listing" must return a list of nodes.

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2129, in run_directive
    'Directive "%s" must return a list of nodes.' % type_name
AssertionError: Directive "meetup-listing" must return a list of nodes.
The full traceback has been saved in /tmp/sphinx-err-KVSNRd.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by zerok** [comment]
Why does it first install Sphinx 1.5.x and then replace it and tons of other stuff with the ones in the requirements.txt? This sounds like the build-code is wrong :(

**Comment by plaindocs** [comment]
Yeah, that does sound odd. @ericholscher any ideas ?

**Comment by plaindocs** [comment]
I suspect it is the RTD default, then the requirements.txt?

**Comment by zerok** [comment]
Looks like it.

**Comment by plaindocs** [comment]
OK, I've got some more perspective on this. RTD runs `make json` as well as `make html` , and that is what is failing the build.  That also fails locally for me.

We've got a few of these:

```
WARNING: The builder has no template manager, ignoring the datatemplate directive.
```

and also 

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/writethedocs-staging/envs/staging/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2129, in run_directive
    'Directive "%s" must return a list of nodes.' % type_name
AssertionError: Directive "meetup-listing" must return a list of nodes.
````

**Comment by zerok** [comment]
Ah, ok 🙂 will try to look into this in the next couple of days once I'm out of the jet lag 🙂

**Comment by zerok** [comment]
Found the issue, PR incoming. Could you please check, though, that `make html` is executed on a clean `_build` folder? If `make json` is done right before `make html`, an empty meetups-page will be generated as the JSON build kind of pollutes a cache. 

Given that pages containing datatemplates already work, though, this should already be the case 😃

**Comment by plaindocs** [comment]
So, We can add an html dependency to the json, but I'm not sure that is desirable.

**Comment by zerok** [comment]
I don't think that will be necessary given that the datatemplate plugin has the same issues we have with the meetup data and there the output is correctly rendered. Perhaps `make json` is executed after `make html` already anyway?

**Pull request merged**
