### PR TITLE
Update gulpfile to gulp 4

### PR DESCRIPTION
**Pull request by plaindocs**
This looks like it might work.

### CODE REVIEW

**Comment by plaindocs** [comment]
Replaces #1056 and takes #1010 into account.

**Comment by plaindocs** [comment]
Browsersync isn't working, but styles is.

**Review by mxsasha — APPROVED** [review]
works for me now

**Comment by plaindocs** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/recipes/minimal-browsersync-setup-with-gulp4.md

**Comment by plaindocs** [comment]
I do wanna highlight that Browsersync still doesn't work here, so if we merge this we should open an issue to fix it. Pretty low priority though.

**Comment by ericholscher** [comment]
This worked for me as well :+1:

**Pull request merged**
