### PR TITLE
Add Prague 2019 CFV blog post.

### PR DESCRIPTION
**Pull request by mxsasha**

### CODE REVIEW

**Comment by mxsasha** [comment]
See https://trello.com/c/6nBySgCR/25-launch-call-for-volunteers

**Review by plaindocs — APPROVED** [review]
LGTM

**Comment by thatdocslady** [comment]
@mxsasha what do you think about pulling in the text from your post into the main Prague post I'm preparing? It'll have the list of talks, then immediately the CFV info.

**Comment by mxsasha** [comment]
> @mxsasha what do you think about pulling in the text from your post into the main Prague post I'm preparing? It'll have the list of talks, then immediately the CFV info.

Yes, as you already did :)
We can close this in favour of #992

**Pull request closed without merging**
