### PR TITLE
Clean up tox & travis configs

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by plaindocs** [comment]
Lemme know when you're done futzing and I'll try to understand what you've changed :-D

**Comment by ericholscher** [comment]
Should be reviewable -- mostly it's just breaking out the tests so that we know what breaks. I wish we could get the matrix in Travis, but didn't want to spend more time on it :)

**Comment by plaindocs** [comment]
Something like

```
env:
  - TEST="lint"
  - TEST="docs"
```

in `.travis.yml` and 

```
[travis:env]
TEST =
    yaml:  yaml-lint
    docs: docs, docs-lint,
```

*ISH*?

**Comment by plaindocs** [comment]
@ericholscher I reckon this does what we want it to, after some futzing. 

I'm pretty close to adding a 4th linter stage over in #732 but can merge that separately.

**Comment by ericholscher** [comment]
Looks good.

**Review by plaindocs — APPROVED** [review]
Gonna merge this in.

**Pull request merged**
