### PR TITLE
Turn Portland sponsors in YAML data

### LINKED ISSUE #516: YAMLize sponsors so we don't have to write lists

### PR DESCRIPTION
**Pull request by ericholscher**
Fixes #516

### CODE REVIEW

**Comment by plaindocs** [comment]
Oh thank you! I've been not finding time for this for months!

**Comment by ericholscher** [comment]
This adds some new sponsors -- would like to merge today if folks could 👍 @writethedocs/core

**Comment by plaindocs** [comment]
Does https://deploy-preview-843--dentist-canary-64055.netlify.com/conf/portland/2019/sponsors/ work for you? 

image

**Comment by plaindocs** [comment]
Yeah, looks like it calls `sponsors.jinja` and that calls `sponsors.html` ?

**Comment by ericholscher** [comment]
Ha, it was overwriting the `sponsors` variable before rendering -- fixed.

**Review by plaindocs — APPROVED** [review]
Although AdNauseum still blocks these by default.

**Pull request merged**
