### PR TITLE
Automatically ish insert video ids into session data file

### PR DESCRIPTION
**Pull request by plaindocs**
I noodled on this one early jetlagged morning, it could certainly be improved, and certainly took me longer than doing it by hand.

I found we've got a lot of old and not working scripts, no yaml dumping utility. :shrug: 

@mxsasha would you mind taking a look and seeing if you think it's worth improving. 

----
:books: Documentation preview :books:: https://writethedocs-www--1965.org.readthedocs.build/

### CODE REVIEW

**Comment by mxsasha** [comment]
I like it! This always takes me more time than I'd like. Using the Levenshtein distance for matching is a great idea. One additional safeguard could be to check that all youtube ID's are unique. Can use a bit of cleanup for sure.

**Comment by plaindocs** [comment]
Thanks @mxsasha 

We've already got that safeguard in the main site code I think? So it's probs not worth adding twice? 

Would you like to be more specific about cleanup? Or do you mean the rest of our code. :-D

**Comment by mxsasha** [comment]
> Would you like to be more specific about cleanup? Or do you mean the rest of our code. :-D

This is what I had in mind: https://github.com/writethedocs/www/pull/1965/commits/4eb6cacb2ef04563635f0dd9619cd451db7bbc68

**Review by mxsasha — APPROVED** [review]

**Comment by plaindocs** [comment]
> > Would you like to be more specific about cleanup? Or do you mean the rest of our code. :-D
> 
> This is what I had in mind: [4eb6cac](https://github.com/writethedocs/www/commit/4eb6cacb2ef04563635f0dd9619cd451db7bbc68)

Thanks @mxsasha ! Easier to do than to explain I reckon. :-D

**Comment by plaindocs** [comment]
OK, I fixed the merge, generated the files. Would you rereview (just double check it looks ship shape)

**Comment by plaindocs** [comment]
What the hell, did this really just add the same ID to every talk?

**Comment by mxsasha** [comment]
> We've already got that safeguard in the main site code I think? So it's probs not worth adding twice?

> What the hell, did this really just add the same ID to every talk?

🤔🤔🤔

**Review by mxsasha — APPROVED** [review]

**Comment by plaindocs** [comment]
> ` [8b5d3e3](/writethedocs/www/pull/1965/commits/8b5d3e32806d7ec90712bce67879693a054698e9)`

Yeah, if you look at [8b5d3e3](https://github.com/writethedocs/www/pull/1965/commits/8b5d3e32806d7ec90712bce67879693a054698e9) before I fixed it now it just added the same ID to every talk. :man_facepalming:

**Pull request merged**
