### PR TITLE
Add Red Hat to AU sponsors

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
This illustrates the backward compatibility issue with dynamic sites again.
Should we just clobber the image? Should we care.

**Comment by ericholscher** [comment]
@plaindocs not sure what you're talking about?

**Comment by plaindocs** [comment]
@ericholscher very fair comment.

I was talking about the `new` suffix in the logo name.

**Comment by ericholscher** [comment]
Ah yea, we can probably just change the old logo to be `old` if we wanted, but we'll have this issue regardless, having to make sure we're pointing at the right image for the sponsor.

**Pull request merged**
