### PR TITLE
Add 2019 Prague speakers

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by plaindocs** [comment]
Made at least one change that'll need a regeneration.

**Comment by plaindocs** [comment]
Final reup please @ericholscher

**Comment by plaindocs** [comment]
Oh, and the thing we can't do with Grorg updates is adding second speakers. :-p

**Review by thatdocslady — APPROVED** [review]

**Review by plaindocs — APPROVED** [review]
I wrote this, it looks fine to me. Cos @thatdocslady said so.

**Pull request merged**
