### PR TITLE
[experiment] Look at linting heading case in the Guide

### PR DESCRIPTION
**Pull request by plaindocs**
I'm not :100: percent sure the GitHub action will work. 

----
:books: Documentation preview :books:: https://writethedocs-www--1850.org.readthedocs.build/en/1850/

### CODE REVIEW

**Comment by plaindocs** [comment]
Might be worth refactoring all of the vale stuff info `.github` as suggested :man_facepalming: 

https://github.com/errata-ai/vale-action#repository-structure

**Comment by plaindocs** [comment]
Damn, finally

image

**Comment by plaindocs** [comment]
@mxsasha @ddbeck @maryaed  please ignore the car crash of commits which will be squashed.

This enforces sentence case on *new commits* in `guide/*`, and also includes a list of old headings which don't match in [Filtered Findings](https://github.com/writethedocs/www/pull/1850/checks?check_run_id=9590381729)

**Review by mxsasha — APPROVED** [review]
💯

**Pull request merged**
