### PR TITLE
Activate CFP and disable landing-only page.

### PR DESCRIPTION
**Pull request by mxsasha**
See https://trello.com/c/ka4dq9Aq/24-launch-cfp
Before merging, we should ensure the news post has the correct date.

Also removes 2018 details from the social event.

### CODE REVIEW

**Comment by plaindocs** [comment]
We need to check the config file has all the info such as ticket prices before making this go live.

**Comment by mxsasha** [comment]
The prices for tickets have been checked through slack, comparing to offsite docs.

**Comment by mxsasha** [comment]
This is now ready for review, the remaining tasks in the card are for when review is complete.

**Review by ericholscher — APPROVED** [review]
Looks good on my side. I did a quick glance around and it looks 💯

**Comment by ericholscher** [comment]
We should merge #655 before this goes live as well.

**Comment by thatdocslady** [comment]
I'm lost between the sponsor PRs, but we need to add the media sponsor (there is a Trello card for it)

**Comment by thatdocslady** [comment]
Also, do we want to start selling tickets already? I can spin up a Tito instance if so

**Comment by thatdocslady** [comment]
A few nitpicks:

- "We’ll let you know if your proposal has been accepted by the Monday, June 2nd." (from CFP page)
- bullets are breaking on the schedule overview page

Otherwise, <3 <3 <3

**Review by plaindocs — APPROVED** [review]
LGTM

**Comment by mxsasha** [comment]
We can start selling tickets too, if it does not delay the CFP - our planned deadline to open the CFP is tomorrow.

**Pull request merged**
