### PR TITLE
Fixed all possible broken links according to travis report

### LINKED ISSUE #734: Fix broken links take two
Supercedes #194, with added HTMLproofer goodness.

We've a few hundred broken links which need fixing:

Example list from 26/11/18: https://travis-ci.org/writethedocs/www/jobs/459836453

Some are just URLs which no longer exist, some are typos, some are misconfigured URLs. 

Most are straightforward fixes.

### PR DESCRIPTION
**Pull request by bandantonio**
Fixes #734

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
This is AWESOME stuff! Thanks @bandantonio !

**Comment by plaindocs** [comment]
According to this https://travis-ci.org/writethedocs/www/jobs/550358430 there is a small number still broken. :-p

We can make exceptions for anything that isn't actually broken using something like https://github.com/gjtorikian/html-proofer#ignoring-content together with http://docutils.sourceforge.net/docs/ref/rst/directives.html#class , such as the `response code 0 means something's wrong` type stuff.

**Comment by bandantonio** [comment]
Yeah, I fixed everything that was actually broken. There were some false alarms for links to holiday inn, for instance and some personal sites. Also, Travis escapes the '@' symbol, so all links to medium automatically become broken. I was telling you about that on Wiring Day in Vilnius

**Comment by plaindocs** [comment]
Yeah, I remember now. 

We can mark each of those as `data-proofer-ignore` then. Or possibly look at double escaping the @ ?

Either way, I'll merge this stuff in! :100:

**Comment by bandantonio** [comment]
> We can mark each of those as `data-proofer-ignore` then. Or possibly look at double escaping the @ ?

I will check Travis report later and try to ignore the rest of links. Probably this would be the last pull pull request.

**Pull request merged**
