### PR TITLE
Adds API link to contributing guide

### PR DESCRIPTION
**Pull request by jimcser**

### CODE REVIEW

**Comment by jimcser** [comment]
Not sure is link is correct one.  Also I have VS Code automatically remove trailing spaces.

**Comment by plaindocs** [comment]
Thanks for the fix!

Probably `/guide/#api-documentation` is a better link, what do you think?

**Comment by jimcser** [comment]
> Probably `/guide/#api-documentation` is a better link, what do you think?

Okay by me.   Edit: Done!

**Comment by jimcser** [comment]
@plaindocs Is there anything else I need to do?

**Comment by plaindocs** [comment]
I'm so sorry @jimcser I gave you  a suggestion about the output, which doesn't work if you just put it like that. You can confirm how that would look here https://writethedocs-www--1450.org.readthedocs.build/guide/contributing/

The following diff shows how to add an id to the title, and then to link to it. 

```diff
diff --git a/docs/guide/contributing.rst b/docs/guide/contributing.rst
index eabca1cd..a5db9909 100644
--- a/docs/guide/contributing.rst
+++ b/docs/guide/contributing.rst
@@ -20,7 +20,8 @@ Where to start
 
 The guide has its origins in the efforts of developers to understand and explain documentation to each other. Since then, Write the Docs has expanded its focus and its community. We've recently reorganized the guide to provide a clearer top-level structure, but there's much work to be done. And you should feel free to suggest further changes to the organization, too. But here are the areas we've most recently identified as needing your contributions: 
 
-* More API docs content! (link)
+* More API docs content! :ref:`api-documentation`
+
 * Helping non-writer roles understand the moving parts of good docs
 * Helping writers new to developer tools or docs-as-code understand the moving parts of new toolchains and workflows
 * High-level discussions of common tools and toolchains. Please avoid advocacy here! But thoughtful presentation of specific use cases, how you solved them, what worked well, and what didn't work so well, are most welcome. If you want to write this kind of topic, consider starting with an issue in GitHub, or contact one of the new guide editors.
diff --git a/docs/guide/index.rst b/docs/guide/index.rst
index 948c8ba4..b06bf448 100644
--- a/docs/guide/index.rst
+++ b/docs/guide/index.rst
@@ -102,6 +102,8 @@ Documentation Guides
 * `Wikiversity Technical Writing <https://en.wikiversity.org/wiki/Technical_writing>`_
 * `Write the Docs <http://www.writethedocs.org/guide/>`_
 
+.. _api-documentation:
+
 API Documentation
 -----------------
```

**Comment by jimcser** [comment]
@plaindocs Looks like it worked, thanks!  I tried to change the text of the link, but I could not find out how
The "Read the Docs' renderer of the pull request is nice.  For future PRs, is there a link or do I just manually change the URL?

**Review by plaindocs — APPROVED** [review]
Nice one!

To see the preview app for each pull request, expand the "Show all checks" section at the bottom, and click 'details'

image

**Pull request merged**
