### PR TITLE
Now that we have 42 meetups!

### PR DESCRIPTION
**Pull request by mjang**

### CODE REVIEW

**Comment by plaindocs** [comment]
Oops.

**Review by plaindocs — APPROVED** [review]
Meetup change looks great! 

Do you wanna revert the package.json stuff (like I tried unsuccessfully to do in the web interface?)

**Comment by mjang** [comment]
> Meetup change looks great!
> 
> Do you wanna revert the package.json stuff (like I tried unsuccessfully to do in the web interface?)

Reverted. PR is now limited to the s/30/40/ bit in index.rst

**Comment by ericholscher** [comment]
🎉

**Pull request merged**
