### PR TITLE
One PR to consolidate the various Writing day Quorum Docs PRs

### PR DESCRIPTION
**Pull request by plaindocs**
Replaces:

-  #1746
-  #1745
- #1743
- #1739

Currently looks like this though, so could use a little reorg:

image

Direct link https://writethedocs-www--1770.org.readthedocs.build/organizer-guide/#meetups

### CODE REVIEW

**Comment by plaindocs** [comment]
My preference would probably be to merge this in as-is, and for someone to commit to cleaning up the structure a little, so we don't let this work languish in PRs for another few months.

**Comment by barbaricyawps** [comment]
@plaindocs , I'm fine with that, if you'd like. Let me know when it's merged.

**Comment by plaindocs** [comment]
@barbaricyawps if you approve it, I'll merge it in right now.

**Comment by rosewms** [comment]
thanks @plaindocs

**Review by barbaricyawps — APPROVED** [review]

**Comment by barbaricyawps** [comment]
@plaindocs : approved.

**Pull request merged**
