### PR TITLE
Vilnius 2019 full website, tickets, CFP

### PR DESCRIPTION
**Pull request by thatdocslady**
TODO:

- [x] Organizer team bios @aidiss (need to create new RST files in /include/ folder, based on the other bios there)
- [x] Venue / city information @aidiss (you can use the format/sections from the Portland/Prague pages)
- [x] CFP form @plaindocs / @mxsasha (whoever has time plz thnx!)
- [x] Tito website @thatdocslady (Tito has a weird bug and I can't generate the ticket website atm)

Questions:

- Are we doing a call for volunteers?

### CODE REVIEW

**Comment by mxsasha** [comment]
I can pick up CFP form. There is no Google Drive folder for Vilnius yet, right?

**Comment by mxsasha** [comment]
CFP form is in Google Docs. Also added it to the config. Responses also end up there.
Form link is https://goo.gl/forms/B4FqgaYHfuAI5aBo1

Accepting responses is currently disabled, it can be enabled on https://docs.google.com/forms/d/1sgUjU3H0xEW_ggjpONFFeuhYwu0ocJSKQ3iNp_9Ll6Y/edit#responses

**Comment by plaindocs** [comment]
Thanks @mxsasha 

I don't see one, but I do have vague recollection of @thatdocslady mentioning one? Maybe the shares are off.

**Review by plaindocs — APPROVED** [review]
This all looks great. When do we want to publish?

@aidiss let me know if you have any trouble adding the Visiting / Venue info.

**Comment by mxsasha** [comment]
Please note that the CFP closing and notification date are currently not set - I wasn't sure what they should be.

**Comment by aidiss** [comment]
>     * Are we doing a call for volunteers?

Yes, let's have a call. It would be great to have extra help.

**Pull request merged**
