### PR TITLE
Remove system messages from the atom feeds

### PR DESCRIPTION
**Pull request by ericholscher**
This stops us from publishing silly messages from RST

### CODE REVIEW

**Comment by plaindocs** [comment]
Unless I'm missing something, that doesn't work, because all of the content is escaped. At least look at the atom file locally shows system messages still in there.

**Comment by ericholscher** [comment]
Are you looking at the right file? It's on the `_absolute.xml` that is processed. It doesn't run by default unless we're on prod, so you need to hack it a bit which is probably silly.

**Review by plaindocs — APPROVED** [review]
OKI doki, confirmed that the `system-message` isn't in https://deploy-preview-1130--dentist-canary-64055.netlify.com/blog/archive/tag/portland-2020/atom_absolute.xml

It *is* in a ton of other atom files though:

```
$ ack system-message _build/html/blog/archive/tag/*/atom.xml | wc
    200    1221   44346
```

So let's merge this and figure out a solution for the rest as well?

**Comment by ericholscher** [comment]
Yea, we can only send email with the `absolute` ones. I could fix all the atom files, but _shrug_.

**Pull request merged**
