### PR TITLE
Added conf branding in desktop view of sub-pages

### PR DESCRIPTION
**Pull request by thatdocslady**
Fresh pair of eyes please :)

Gist: Copied the logo-mobile SVG files, renamed them to *-subpage, and embedded the display code in the header of the *-content template.

### CODE REVIEW

**Comment by ericholscher** [comment]
Are the SVG files different in some way?

**Comment by thatdocslady** [comment]
Nope. They're identical to the *-mobile.svg files, except the file name is different. And yes, I tried reusing the mobile svgs first, but it didn't work.

**Comment by ericholscher** [comment]
Weird. What didn't work?

**Comment by thatdocslady** [comment]
They wouldn't display. Don't ask me why, I have no idea :( feel free to play around with it if you want, but I'm not sure if it's a deal-breaker for this PR?

**Comment by ericholscher** [comment]
Also, looks good: http://writethedocs-staging.readthedocs.io/en/staging/conf/na/2017/news/announcing-tickets-cfp-website/ :)

**Comment by plaindocs** [comment]
Awesome :-)

**Pull request merged**
