### PR TITLE
Switch to Python 3.5

### PR DESCRIPTION
**Pull request by plaindocs**
Address  #451

So this fixes the Netlify problem which is good to know.

I've tested the combo of Python 3.5 *and* Video archive over in 
https://github.com/writethedocs/www/tree/sw-python-35-and-videos and #453 

~I've used Pipfile for dependencies, rather than fiddling with multiple venvs, should disentangle that before merging. Also seems ok. Not sure about merging both of these in one go.~ :trollface:

### CODE REVIEW

**Comment by plaindocs** [comment]
I've diffed the html output and it looks mostly fine. 
Some unicode stuff that still displays ok as html.

**Comment by ericholscher** [comment]
Looks good to me! I'm a fan of moving more of my life to py3. We should also update our install docs though.

**Comment by plaindocs** [comment]
Yeah, I'll update the README and merge.

Thoughts on Pipfile vs requirements.txt?

**Comment by ericholscher** [comment]
People seem to like pipfile, I haven't really used it. I'm fine switching to it, as long as we document how to use it :)

**Comment by ericholscher** [comment]
(Though I don't think RTD supports it yet)

**Comment by plaindocs** [comment]
Right, in that case `requirements.txt` it is.

**Comment by plaindocs** [comment]
:shipit: ?

**Comment by ericholscher** [comment]
👍

**Pull request merged**
