### PR TITLE
Add RTD GH action for previews

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
This looks like it should do what it says :-p :man_shrugging:

**Comment by mxsasha** [comment]
Puzzled by how this is different from the read the docs build we had already?

**Comment by plaindocs** [comment]
@mxsasha GH Actions don't run for new PRs by people who aren't in the org.

**Comment by ericholscher** [comment]
This adds a comment to the description, in theory.

**Pull request merged**
