### PR TITLE
update vale config with EU rule

### PR DESCRIPTION
**Pull request by eirinikos**

### CODE REVIEW

**Comment by plaindocs** [comment]
So, the other thing we *could* do if this proves tricky, is instead of linting the output 
`_build/html/conf/prague/*.html` ....

Put the checks in the input again, like the original, and check both the `*.rst` *and* the `docs/_data/config-prague-2018.yaml` . Still more error prone I think.

**Comment by plaindocs** [comment]
Also - IF we do get the Portland checks to work, we'll need to figure out which ones are legit.

https://valelint.github.io/docs/config/#using-comments

**Comment by plaindocs** [comment]
And finally, the `$` is definitely problematic. 

Docs (go docs that is) seem to suggest `$$` might work, but doesn't seem to for me.

**Comment by jdkato** [comment]
If you'd like to avoid calling Vale twice, I'd recommend a slight restructuring to this PR:

1. Make `EU` its own style (rather than a rule within the `WTD` style) and update the rule definition:

    ```yaml
    # Place in `vale/EU/Portland.yml` (or similar).
    extends: existence
    message: "Prague pages should not include Portland-ish terms like '%s'."
    level: error
    nonword: true
    tokens:
      - '(?:\$[,\d]+|Portland)\b'
    ```

   (See [this regex101 session](https://regex101.com/r/04AGLX/1/) for details.)

2. Change the `.vale` config to:

    ```ini
    StylesPath = vale
    MinAlertLevel = warning

    [docs/conf/prague/**/*.{rst}]
    BasedOnStyles = EU

    [docs/_data/config-prague-2018.yaml]
    BasedOnStyles = EU

    [*.{md,rst,txt,json}]
    BasedOnStyles = WTD

    vale.Redundancy = YES
    vale.GenderBias = YES

    TheEconomist.UnnecessaryWords = YES
    TheEconomist.Hectoring = YES
    ```
3. Change `vale --glob='!_data/*' .` to `vale .` in the `tox.ini` file.

Using this configuration, I get the following results:

```console
$ vale docs

 docs/about-us.rst
 36:240  warning  'for free' - See section        TheEconomist.UnnecessaryWords 
                  'Unnecessary words'                                           
 51:27   warning  'for free' - See section        TheEconomist.UnnecessaryWords 
                  'Unnecessary words'                                           

 docs/conf/prague/2018/convince-your-manager.rst
 23:40  error  Prague pages should not         EU.Portland 
               include Portland-ish terms                  
               like 'Portland'.                            
 32:56  error  Prague pages should not         EU.Portland 
               include Portland-ish terms                  
               like '$450'.                                

 docs/conf/prague/2018/sponsors/prospectus.rst
 44:40  error  Prague pages should not         EU.Portland 
               include Portland-ish terms                  
               like 'Portland'.                            

 docs/organizer-guide/confs/sponsorship.rst
 21:71  warning  Use 'e.g.,'  WTD.Abbreviations 

 docs/organizer-guide/newsletter/editorial-guidelines.rst
 17:36  warning  Use 'i.e.,'  WTD.Abbreviations
```

(Also, given the nature of the rule, it might make sense to make it a `warning` rather than an `error`.)

**Comment by plaindocs** [comment]
Hey there @jdkato thanks for popping in. :-)  

That post is extremely helpful. 

I suspect we'll end up testing some thing in the `rst` and some in the `html` due to the complexity of the build system -- but we were already figuring out that we needed to move the test in this PR to a separate style. :+1: 

Was there a reason you put the `$` in the same token as the `Portland`?

**Comment by jdkato** [comment]
> Was there a reason you put the $ in the same token as the Portland?

No - it was just easier to test with regex101. The only tricky part, as you noted above, is handling the `$`. The cleanest way to do this is probably to make it two rules:

```yaml
extends: existence
message: "Prague pages should not include Portland-ish terms like '%s'."
level: error
tokens:
  # This becomes `\b(?:Portland|another term)\b, which wouldn't work with the `$`.
  - Portland
  - another term
```

and

```yaml
extends: existence
message: "Prague pages should not include '%s'."
level: error
raw:
  - '\$[,\d]+'
```

**Comment by plaindocs** [comment]
@eirinikos lets also test the html output for `{{` and `}}` which are templating errors

**Comment by eirinikos** [comment]
I made some preliminary changes based on @jdkato 's feedback (thanks!) ...

One thing:
For some reason, none of the `config-_____-2018.yaml` files are showing up in my clone, though I do see them in the [upstream master](https://github.com/writethedocs/www/tree/master/docs/_data).

I had just run `git pull` on Tuesday prior to making these changes. Were these files merged into the master from another branch?

Just doing a sanity check with a very tired brain. ☺️

**Comment by plaindocs** [comment]
Hey @eirinikos 

If you're working on your own fork you need to merge upstream as described in

https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by plaindocs** [comment]
EDIT: resolved

**Comment by plaindocs** [comment]
Also, I had yet another thought: instead of running vale twice, we just move the vale check to *after* running sphinx, and add a custom grouping for the html output. :tada:

**Comment by eirinikos** [comment]
(N.B. We are transferring this work to #472.)

**Pull request closed without merging**
