### PR TITLE
More site updates.

### PR DESCRIPTION
**Pull request by ericholscher**
This branches from #370 and adds additions on my side.
In particular:

* Removes most of the duplipcated templates which didn't serve a purpose
* Allows us to set the banner image with RST metadata
* Adds a few more fancy banners
* Uses includes for menus, so reduce duplication

### CODE REVIEW

**Comment by ericholscher** [comment]
Would be great to get the other content pages checked out (I found a few errors) since we weren't linking to them before! @thatdocslady @plaindocs

**Comment by thatdocslady** [comment]
@ericholscher we have a separate issue for tracking content updates #368 , and I'd feel much more comfortable if we merged the design fixes first so that I'm not breaking the internet.

I see now that this PR includes @xpostudio4 's fixes from PR #370, so I will merge this PR and kill the other one. This way we have the latest fixes merged and low risk of conflicts.

Then, I will consolidate the last bits of design fixes in the existing issue and notify everyone of the current status.

**Comment by ericholscher** [comment]
This PR contains Leo's PR, so that one is now done too.

**Comment by ericholscher** [comment]
Well, the design updates made the content updates go live (we're linking to all the content page) -- so you can't easily separate them.

**Pull request merged**
