### PR TITLE
Created workshop announcement and updated index page

### PR DESCRIPTION
**Pull request by thatdocslady**
I know it's kind of a slim announcement, but honestly the two important things there are "buy tickets for this" and "read all the info on the website", no?

### CODE REVIEW

**Comment by ericholscher** [comment]
We mentioned the workshops in the last announcement, and IIRC we never sent it to the main email list (http://www.writethedocs.org/conf/na/2017/news/announcing-presentations/) -- so might be worth sending that as well?

**Review by plaindocs — APPROVED** [review]

**Comment by thatdocslady** [comment]
@ericholscher I'm still waiting for the testing on the mailchimp theme so that we can update the global template and then I can author and send an NA announcement with all those things. I wanted to have a blog post set up on the website so that we can link to it (also when I send a message via Tito to people who already got tickets).

**Comment by thatdocslady** [comment]
Hmm. Now that I think about it a bit more, maybe instead of creating a separate announcement for the workshops I can back-change the previous blog post, and then link from there to the workshops page (and then link to *that* from the mailchimp/tito messages)?

**Comment by plaindocs** [comment]
I don't think the extra news item is a bad thing. I'd leave it as is.

**Pull request merged**
