### PR TITLE
Closed CFP

### PR DESCRIPTION
**Pull request by swapnilogale**

### CODE REVIEW

**Comment by swapnilogale** [comment]
@plaindocs - can you help me with the Travis CI build?

**Comment by ericholscher** [comment]
@swapnilogale it looks like travis is passing. Anything I can do here?

**Comment by swapnilogale** [comment]
@ericholscher could have been a temporary glitch. It's worked, but the home page does not seem to have refreshed. The preview here looks correct though.

**Comment by swapnilogale** [comment]
The preview shows this:
image

The actual live site still has the Speak button visible:
image

**Comment by ericholscher** [comment]
Right, this hasn't been merged. It won't go live until we merge it.

**Comment by swapnilogale** [comment]
Aah ok. Forgot that bit. Can we merge it in please? No issues otherwise.

**Comment by ericholscher** [comment]
👍

**Comment by plaindocs** [comment]
Ah sorry folks, I sorted the build failure (was a network glitch, so I just restarted the build - but didn't reply here.

**Pull request merged**
