### PR TITLE
Video archive for the conferences

### PR DESCRIPTION
**Pull request by zerok**
This so far only includes video pages for the conferences using the *.*.speakers.yaml data file format. I'd propose that we handle meetups in a different PR.

This is based on #239 . Big thanks to @xpostudio4 for his layouts 😄

### CODE REVIEW

**Comment by zerok** [comment]
The build breaks right now because it is expecting the data from #295 to be there.

**Comment by plaindocs** [comment]
Awesome, I'll have a play around with this, and see if I can break it.

**Comment by zerok** [comment]
Awesome, thanks :) I've merged the updated master and the build now goes through :)

**Comment by ericholscher** [comment]
Got this running locally with a bit of futzing. Looks good to me!

**Comment by zerok** [comment]
@ericholscher Awesome! Thank you :D

**Pull request merged**
