### PR TITLE
Adds OpenStack to NA 2017 Writing Day

### PR DESCRIPTION
**Pull request by annegentle**
@meker12 @Bradamant3 I can help out, but don't feel obligated to add OpenStack if you think it's not needed. Edit at will, or close PR if needed.

### CODE REVIEW

**Comment by meker12** [comment]
My philosophy is "the more; the merrier".  I think that the OpenStack project is a good project for people who want to learn the contribution workflow and get experience with collaborative editing. Asking @plaindocs to review for merge. He's been coordinating writing day activities.

**Comment by plaindocs** [comment]
Seems reasonable. There is a lot of text and not much info on what you want to do on the day though.

**Comment by annegentle** [comment]
Thanks @plaindocs -- I can add detailed instructions for picking up bugs labeled with `low-hanging-fruit` if that's helpful.

**Comment by plaindocs** [comment]
No need I think - if you're gonna be there in person to coordinate that'll be enough.

**Pull request merged**
