### PR TITLE
fix:  italics where it APPEARS to have been intended...

### PR DESCRIPTION
**Pull request by vwheeler63**
...and ended up "_like this_" inside an .RST file which merely puts underscores on either side of the terms which APPEAR to have been intended to be standard "emphasized" words.  This appears to be a possible export-translation error from some software, which put the syntax for Markdown _italics_ rather than reStructuredText *italics*.

I saw one of these while I was reading and decided to LOOK for such occurrences throughout the website .RST files and found these 5 occurrences.

An issue was not created for this.

----
📚 Documentation preview 📚: https://writethedocs-www--2219.org.readthedocs.build/

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
Sounds right to me. Could just be folks thinking rst but writing markdown as well, I know I do it enough.

Thanks for looking and fixing.

**Comment by vwheeler63** [comment]
> Sounds right to me. Could just be folks thinking rst but writing markdown as well, I know I do it enough.
> 
> Thanks for looking and fixing.

My pleasure!  It appears this repository is set to only permit a merge if the the commit is based on the tip of `master` branch by the time it is ready to merge (I'm getting "This branch is out-of-date with the base branch" message).  So I will rebase these changes on `master`.

**Comment by vwheeler63** [comment]
@plaindocs Hi, Sam!  Thank you for the invitation to collaborate!  I'm honored!  😃

**Comment by plaindocs** [comment]
Always great to see folks interested in helping fix stuff!

**Pull request merged**
