### PR TITLE
Force default file encoding to UTF8 on windows

### PR DESCRIPTION
**Pull request by grisevg**
Force default file encoding to UTF8 on windows. Otherwise it crashes when opening non-ascii files on windows.

### CODE REVIEW

**Comment by plaindocs** [comment]
@ericholscher you know of any reason not to do this?

**Comment by grisevg** [comment]
I'm really not sure if it's correct thing to do or not
This old SO post (from 2010) says it's bad https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by ericholscher** [comment]
It sounds like this shouldn't be necessary with python3 (and the SO post says it doesn't do anything). Were you running this with python3?

I don't have access to a windows machine, but I'm happy to include this if it fixes things for windows users though.

**Comment by grisevg** [comment]
Yes, I tried both Python 3.6 and Python 3.7, same thing on both.

**Review by ericholscher — APPROVED** [review]
Seems worth trying. :+1:

**Pull request merged**
