### PR TITLE
Add sponsors

### PR DESCRIPTION
**Pull request by plaindocs**
@ericholscher 
Can you sanity check this for me?

Do we need to leave the mediums on their own row, and only have the small in multi column? Ah, I need to fix up.

### CODE REVIEW

**Comment by plaindocs** [comment]
Still not perfect. I wonder if we could setup sponsorship levels in CSS?

**Comment by ericholscher** [comment]
No, they are paying us a good deal less, and should have a small logo. Guessing the prospectus is wrong there, but we should just make it a small logo.

**Comment by ericholscher** [comment]
Also dislike how strongly the sponsors are shown on the front page. We should probably add more content there, so that it doesn't just feel like a brochure for them.

**Comment by plaindocs** [comment]
I'm less bothered by the front page, as it is going to be past the scroll for most people (I think) so... But we can add some more newsy item blocks.

**Pull request merged**
