### PR TITLE
Update site & styles for 2019

### PR DESCRIPTION
**Pull request by ericholscher**
This adds a link to the PDX dates on the conf index and a landing page for 2019. It uses last years colors for now.

### CODE REVIEW

**Comment by plaindocs** [comment]
At first glance all the images are broke, presumably because we didn't copy the dir over to 2019?

**Comment by plaindocs** [comment]
FF on Linux: 

image

**Comment by plaindocs** [comment]
Looks fixed on my laptop.

**Comment by plaindocs** [comment]
And looks great on Chrome on Android.

**Review by plaindocs — APPROVED** [review]
We should double check the Firefox Focus thing at some point. 

Looks great. NB I've not checked all 400 changed files :-p

**Comment by plaindocs** [comment]
* [ ] Day stickers
* [x] Social icons
* ~[ ] maybe the menu?~

**Comment by ericholscher** [comment]
>  maybe the menu?

Any more detail here?

**Comment by plaindocs** [comment]
Yeah, ignore that. I had a vague memory of the menu drop down being coloured as per theme, but checking the main site, it isn't.

**Comment by plaindocs** [comment]
Yeah, ignore that. I had a vague memory of the menu drop down being coloured as per theme, but checking the main site, it isn't.

**Comment by plaindocs** [comment]
Yeah, ignore that. I had a vague memory of the menu drop down being coloured as per theme, but checking the main site, it isn't.

**Comment by plaindocs** [comment]
Yeah, ignore that. I had a vague memory of the menu drop down being coloured as per theme, but checking the main site, it isn't. 

I'd vote for hiding the green stickers from view, and merging this in, thoughts?

**Comment by plaindocs** [comment]
Yeah, ignore that. I had a vague memory of the menu drop down being coloured as per theme, but checking the main site, it isn't. 

I'd vote for hiding the green stickers from view, and merging this in, thoughts?

**Comment by ericholscher** [comment]
Yea, all the info is still there, and we can add them in once we color them 👍 Will fix it up & ship it tomorrow.

**Comment by plaindocs** [comment]
Oh btw, we've got an empty menu in the Mobile version. 

photo5942529850852093579

**Comment by ericholscher** [comment]
Yea, the menu is hidden. I didn't hide the menu button tho, but could probably manage that as well.

**Comment by plaindocs** [comment]
+1 for hiding the button.

**Pull request merged**
