### PR TITLE
Add emoji to the topics page

### PR DESCRIPTION
**Pull request by ericholscher**
This makes it a bit easier to tell what the content type of each link is

Preview here: https://writethedocs-www--1236.org.readthedocs.build/topics/#writing-words

### CODE REVIEW

**Review by mxsasha — APPROVED** [review]
💯

**Review by plaindocs — APPROVED** [review]
:100:

**Review by bethaitman — APPROVED** [review]
You superstar, thank you for doing this! Huge improvement

**Comment by plaindocs** [comment]
The other thing that might be interesting for this kinda content - is looking at a two column layout.

**Comment by ericholscher** [comment]
@plaindocs Yea, I think there's a lot more we could be doing with this content. I'd like to get it properly tagged so that we can do a bit more with it on the detail pages as well. Baby steps tho :)

**Pull request merged**
