### PR TITLE
Add Good Docs Project to 2022 Prague Writing Day

### PR DESCRIPTION
**Pull request by barbaricyawps**
This PR is to add our project to the list of Writing Day projects for Prague 2022.

Please let me know if you need me to take any additional action for Writing Day!

----
:books: Documentation preview :books:: https://writethedocs-www--1795.org.readthedocs.build/en/1795/

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
LGTM

If you felt that like opening a PR to remove all of the other Writing Day projects, which were carried over from last year, that would be very welcome.

**Comment by barbaricyawps** [comment]
Thanks so much @plaindocs ! I'm actually not seeing the other Writing Day projects. Can you tell me which topic you're looking at?

**Comment by plaindocs** [comment]
Oh my apologies @barbaricyawps I must have glanced at the wrong file.

**Comment by barbaricyawps** [comment]
@plaindocs , no worries at all! I'm happy to help. 😄

**Pull request merged**
