### PR TITLE
Bump sphinx and ablog

### PR DESCRIPTION
**Pull request by plaindocs**

### CODE REVIEW

**Comment by plaindocs** [comment]
@ericholscher I've bumped some version numbers to see if it fixes the build problem. Any objctions to merging?

**Comment by ericholscher** [comment]
Nope, looks good.

**Comment by ericholscher** [comment]
@plaindocs is there a specific issue that this is fixing? Not sure why it'd randomly start breaking, unless we're doing something new :)

**Comment by plaindocs** [comment]
I can't see a cause. There is an error in the atom.xml generation. But I'm at a bit of a loss as to why. Works OK locally, and on netlify. Take a look at the RTD build log and see if you have a better suggestion?

**Comment by ericholscher** [comment]
Looks like this is the issue: https://github.com/abakan/ablog/issues/74#issuecomment-369167516

Not sure why it randomly started happening now though :/

**Comment by ericholscher** [comment]
Oh. I bet the ablog fork we were using got updated. Didn't realize we were pinning it to github :/

**Comment by plaindocs** [comment]
Maybe, don't think we were pinning to a commit.

**Comment by ericholscher** [comment]
Of course bumping sphinx caused some other issues -- fixing :)

**Comment by ericholscher** [comment]
The website should now be updated properly at least 👍

**Pull request merged**
