### PR TITLE
Tickets as RST

### PR DESCRIPTION
**Pull request by plaindocs**
Fix for #368 

So someone needs to fix up the CSS on this PR to make it look how it should look. @thatdocslady @ericholscher ?

Two gotchas:

- [ ] Can't see an easy way of floating the price right like in the current page. Maybe

    ```rst
    .. class:: price
        450
    ```

    and some CSS wizardry to make it H2 ish ?

- [ ] Text block after sections is problematic. Hence the title hack.

### CODE REVIEW

**Comment by thatdocslady** [comment]
I'm wondering if we're overkilling this somehow, maybe it's better to just do a clean RST text list (or use a deflist directive if it's a thing). Are we trying to make this specific section more modular/reusable?

**Comment by plaindocs** [comment]
Not overthinking. I can remove classes if people prefer, and leave it formatted like the rest of the pages - but if we want to maintain the same sort of formatting as it has already we need to classify (see what I did there) the RST.

**Comment by ericholscher** [comment]
I like having the little design flourishes -- I think it's what makes it distinct from our 2016 site, which was literally just a basic skin around a bunch of bare RST.

**Comment by ericholscher** [comment]
eg. http://www.writethedocs.org/conf/na/2016/#tickets

**Comment by plaindocs** [comment]
Thanks @xpostudio4

**Pull request merged**
