### PR TITLE
Yamale schema fixed and data value changed.

### PR DESCRIPTION
**Pull request by Reezaali**

### CODE REVIEW

**Comment by plaindocs** [comment]
Thanks @Reezaali this is an excellent start. I'll make the yaml files more consistent so they all validate before merging this in.

**Comment by plaindocs** [comment]
@ericholscher we need to resolve the day issue that cropped up in #495 before committing this.

**Comment by ericholscher** [comment]
This is a neat approach. I will see what I can do w/ the `days` stuff, but I think this looks like a good way to make sure we keep our YAML in sync. 💯

**Comment by ericholscher** [comment]
Got this working. Pretty neat 💯

**Comment by plaindocs** [comment]
It is, and I owe @Reezaali some apologies for letting it languish for so long.

**Comment by plaindocs** [comment]
Merging it in with a failing test seems an odd choice though? 

What do you think about removing 

```
date.day_one.dotw: Required field missing
date.day_two.dotw: Required field missing
```

checks?

**Comment by ericholscher** [comment]
I fixed the tests before merge, I just couldn't push back to this branch

**Comment by plaindocs** [comment]
:-o - was showing me them still broken. :+1:

**Pull request merged**
