### PR TITLE
Announce speakers prep

### PR DESCRIPTION
**Pull request by plaindocs**
@ericholscher Grorg is cleaned up, and first batch of pics from the form are here.

### CODE REVIEW

**Comment by plaindocs** [comment]
I've added speakers to the front page, doesn't look great yet.

**Comment by ericholscher** [comment]
Let's just leave the speakers off the front page for now.

**Comment by ericholscher** [comment]
Looks like the images need to be resized, but I don't want to deal with it right now. We just need to get the talks announced.

**Comment by ericholscher** [comment]
Could also just kill the images, and use the names.

**Comment by ericholscher** [comment]
Tried a few things. Pushed up something workable-ish with no speakers on the front page :)

**Comment by plaindocs** [comment]
Lol at tooing and froing on the index page. This stuff should not really be a pain.

Anyhow, I'm happy for this to go out as is, I'm creating a separate issue for minor tweaks.

**Pull request merged**
