### PR TITLE
Tweaking meetup stuff

### PR DESCRIPTION
**Pull request by plaindocs**
* Fix long urls to `:doc:` format
* Suggested format for listing meetup orgs - we can put a call out in `#meetup-organisers` and ask people to add their twitter handle
* Clarified who to contact about what. @mjang - you prefer being listed by name or not? I can just point people to `#meetup-organisers` if you prefer?

### CODE REVIEW

**Comment by mjang** [comment]
#meetup-organizers is probably best. If you need a name, list both me and @meker12 (if that's OK with her)

Good idea about a list of twitter handles -- maybe email addresses as well?

**Comment by plaindocs** [comment]
OK, I've left the who to contact stuff generic.

Emails + Twitter feels like overkill to me. It'll end up cluttered, and I don't really expect many people to use this way to contact meetup org, but more a way of making the work organisers are doing visible. But I'm happy to be persuaded if anyone feels strongly.

**Comment by mjang** [comment]
Emails + Twitter is probably overkill -- however, it'd be helpful to have one alias for all Meetup organizers.

**Review by ericholscher — APPROVED** [review]
Merge away!

**Comment by plaindocs** [comment]
@mjang definitely - but that is an internal thing, not a public alias.

**Comment by mjang** [comment]
Twitter handles: (others are welcome to edit this comment and add their meetup/handle names)

Portland: @WriteTheDocsPDX

**Comment by FelicianoTech** [comment]
I don't seem to have the ability to edit @mjang's comment so I'll add mine here:

New York City: @WriteTheDocsNYC
Philadelphia: @WriteTheDocsPHL (in-progress, will be polished before March is over)

**Comment by plaindocs** [comment]
Cheers Mike, Feliciano, 

Yep - you can't other people's comments, so just add the twitter handles in new comments.

**Comment by ericholscher** [comment]
This should probably be merged soon before it gets more conflicts :+1:

**Comment by plaindocs** [comment]
Fair. I was hoping for some more twitter handles, but will merge these for now.

**Pull request merged**
