### PR TITLE
Ship the AU 2022 website

### PR DESCRIPTION
**Pull request by swapnilogale**
Updated the conf website for AU 2022 conference.

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
Looks like a good start. Approving now so you can merge it when you're ready.

**Comment by swapnilogale** [comment]
@thatdocslady @plaindocs this is all set up to go. If you could please give this a quick eye-over, we can ship it :)

**Review by plaindocs — APPROVED** [review]
LGTM

**Comment by plaindocs** [comment]
Though the CFP isn't live, right?

**Comment by swapnilogale** [comment]
> Though the CFP isn't life, right?

I toggled it to live in Pretalx. Is that what you mean?

**Comment by plaindocs** [comment]
@swapnilogale the form isn't showing on the CFP page for me? But maybe I checked before you toggled it in Pretalx?

**Comment by plaindocs** [comment]
Looks good now.

**Pull request merged**
