### PR TITLE
Framework for some kind of AU day

### PR DESCRIPTION
**Pull request by plaindocs**
An almost certainly incomplete list of things to fix:

- [x] remove content (news pages and TOC, sponsors, most of index page)
- [x] check for `Prague`, `eu`, etc
- [x] rename or remove `boat.rst`
- [x] ticket links
- [x] logo assets

When removing pages remove *both* links in `_templates/2017/au-menu.html`

More work needed in

- [x] speaker / schedule / data setup / speaker templates
- [x] split morning / afternoon and link from index

### CODE REVIEW

**Comment by plaindocs** [comment]
Waiting for web assets from @thatdocslady 

@swapnilogale do you want to have a look at content and let me know what you need help with

**Comment by plaindocs** [comment]
Hey @swapnilogale . Do you plan to have

* [x] ~unconference?~
* [x] ~lightning talks?~
* [x] writing day?

**Comment by ericholscher** [comment]
Believe they are doing a half-day writing day.

**Comment by swapnilogale** [comment]
We have a half day doc fix-it/sprint activity. Won't have enough time for unconference or lightning talks.

**Comment by plaindocs** [comment]
~@ericholscher could you take a cursory glance at 6bdcc90 please~

No need it is filled vs skeleton.

**Comment by plaindocs** [comment]
@swapnilogale I'm guessing we also want to remove the whole welcome wagon concept?

**Comment by plaindocs** [comment]
OK, I'm guessing that is about good to go. We should add some placeholder info about the social, so people can plan for it, even if we don't have details.

**Comment by plaindocs** [comment]
OK, if ONE of you could give this another pair of eyes and let me know, I'll merge it in.

**Comment by swapnilogale** [comment]
Reviewed. Happy for this to be merged.

**Review by swapnilogale — APPROVED** [review]
Happy with the website copy. Once we have the ticketing working, we should be good to go.

**Comment by plaindocs** [comment]
:tada: :tada: :tada: :australia:

**Pull request merged**
