### PR TITLE
Au conf so

### PR DESCRIPTION
**Pull request by swapnilogale**

### CODE REVIEW

**Comment by ericholscher** [comment]
@swapnilogale this PR just reverted a bunch of other changes on our website. You need to be careful that you aren't reusing branches, this can cause many issues for us :/

**Comment by swapnilogale** [comment]
Sorry @ericholscher. Should I be creating new branches each time I make changes?

**Comment by ericholscher** [comment]
Yea, and confirming in the "Files Changed" view (https://github.com/writethedocs/www/pull/646/files) that you aren't deleting stuff you don't mean to :)

**Comment by swapnilogale** [comment]
Yikes! I didn't mean to delete anything and I definitely don't remember manually doing so. I only change au files?

**Comment by ericholscher** [comment]
Yea, it was because you merged an old branch that didn't have the changes. I'm not 100% sure why git/github is doing that, but alas :)

**Comment by swapnilogale** [comment]
Strange. Only happened this once. Anyways, I will create a new branch for these new changes I am working on.

**Pull request merged**
