### PR TITLE
Make the templates for 2018 generic.

### PR DESCRIPTION
**Pull request by ericholscher**
This was done when adding the Cincy conf to the site. Now we don’t have
city-specific templating, but just a base set of templates for each year,
except for the menus (for now).

This allows us to generate all the interesting bits & pieces from the YAML
file, without having to customize each set of templates.

### CODE REVIEW

**Comment by plaindocs** [comment]
Ooh nice!!

This looks like we should be able to delete 

```
eu/generic.html
eu/index.html
na/generic.html
na/index.html
base_na.html
base_eu.html
```

and refactor till things aren't broken, right? 

Then we need to fixup the speaker template and move it out of NA

**Review by plaindocs — APPROVED** [review]
Cincinnatti looks great.

Do we need a newsletter segment? 
And we should probably automate the list of confs as well at some point. :-p

**Comment by plaindocs** [comment]
I also like the data format for the three days  -although we'll need to figure some more standardization for that.

**Comment by ericholscher** [comment]
Yea we should be able to delete all the customized templates and use flags, I just didn't get around to the menus yet.

**Comment by plaindocs** [comment]
I'm working on this fixups here btw.

**Comment by plaindocs** [comment]
Urgh, waat. Those [conflicting files] haven't been changed for ages.

**Comment by plaindocs** [comment]
They are just deletions anyway I think.

**Comment by ericholscher** [comment]
@plaindocs think we should ship this? Cincy isn't linked up yet, but I want to get this out before the templates diverge more.

**Comment by ericholscher** [comment]
heh, not quite ready yet: 

screenshot 2018-04-10 12 42 03

**Comment by plaindocs** [comment]
HA! I had to fix a couple of the conditions on the templates already, because non existing key seems to test as true. :-p

I'll take a look.

:+1: to merging sooner rather than later.

**Comment by ericholscher** [comment]
Yea, not sure where those dates are coming from. Perhaps we're not properly overwriting the context variables or something.

**Comment by plaindocs** [comment]
OK, I *think* we can merge this - wanna take it for a quick spin beforehand?

**Comment by plaindocs** [comment]
:+1:

**Pull request merged**
