### PR TITLE
Added Google as sponsor

### PR DESCRIPTION
**Pull request by swapnilogale**

### CODE REVIEW

**Comment by swapnilogale** [comment]
@plaindocs  why can't I preview the changes? It used to come up with the netlify address?

**Comment by plaindocs** [comment]
The PR build look glitchy, not sure why.

The most recent preview is https://5b9c69e073f2cf1c573ba7af--dentist-canary-64055.netlify.com/conf/australia/2018/

**Comment by plaindocs** [comment]
There you go.

**Comment by swapnilogale** [comment]
Thanks @plaindocs - can you please review/approve and merge this?

**Comment by ericholscher** [comment]
Moved the HTML to make it just 1 line vertically to align better, but sponsorship logos are _always_ a pain, so :shrug:

**Review by plaindocs — APPROVED** [review]
LGTM

**Comment by plaindocs** [comment]
@swapnilogale merge at will

**Pull request merged**
