### PR TITLE
Add mention of AU conf coming soon

### PR DESCRIPTION
**Pull request by ericholscher**
This is a placeholder for the AU conf.

cc @swapnilogale

### CODE REVIEW

**Comment by plaindocs** [comment]
LGTM

**Review by plaindocs — APPROVED** [review]

**Comment by plaindocs** [comment]
Shall I just merge this in? Or are we waiting on anything.

**Comment by ericholscher** [comment]
Feels like we're close to dates, so we can go ahead and wait on those.

**Comment by swapnilogale** [comment]
@ericholscher @plaindocs - we have decided on dates for AU conference - 15th and 16th Nov 2018. Location: Melbourne
Do we need more info except for this at this stage?

**Comment by plaindocs** [comment]
I think we've got a strong preference to announce the dates after the venue confirmation.

**Comment by ericholscher** [comment]
This now has a basic AU site landing page: https://deploy-preview-459--dentist-canary-64055.netlify.com/conf/au/2018/

Agreed that we should wait to announce dates until we have a venue, since locking ourselves into dates makes it much harder to get a venue in case our preferred one is already booked.

**Comment by ericholscher** [comment]
Calling the venue today to confirm the venue, calling this shippable :)

**Pull request merged**
