### PR TITLE
Testing documentation build

### PR DESCRIPTION
**Pull request by benoitbryon**
This pull request introduces tests for the documentation:
- added a `test` target to project's Makefile
- fixed documentation so that tests actually pass
- added a "use doctests" recommendation... and applied it to docs.writethedocs
- introduced a .travis.yml for use with https://travis-ci.org/ => **needs workaround**: enable TravisCI hook on Github repository, check that the provided .travis.yml works fine (I didn't test it).

If the pull request is merged (and TravisCI enabled), we will get "documentation build" status, including for pull requests. Contributors will be committed to build success (not only involved into).

### CODE REVIEW

**Comment by benoitbryon** [comment]
Notice that I may package this tool as a standalone project, then use it here instead of include it here.
Imho, those tests aren't specific to docs.writethedocs (in fact, I already applied them on some other projects).
So I guess it could be packaged in a separate project, then used by docs.writethedocs, and also by other documentations.
=> "test your builds" could be a recommendation!

**Comment by ericholscher** [comment]
+1 for having it external.

**Comment by benoitbryon** [comment]
@ericholscher said:

> +1 for having it external

Done:
- moved tests to https://github.com/benoitbryon/sphinxcontrib-testbuild
- used this new project as an external tool

Notice that I enabled Travis-CI for the external tool: https://travis-ci.org/benoitbryon/sphinxcontrib-testbuild/builds

**Comment by benoitbryon** [comment]
Released sphinxcontrib-testbuild on PyPI:
- http://pypi.python.org/pypi/sphinxcontrib-testbuild
- http://sphinxcontrib-testbuild.readthedocs.org/en/latest/

**Comment by benoitbryon** [comment]
Enabled Travis-CI for this fork: https://travis-ci.org/benoitbryon/docs.writethedocs/builds
=> it works :)

**Comment by ericholscher** [comment]
Awesome! :)

Let's go ahead and merge this, and we can get the awesomeness for the main
repo :)

On Mon, Feb 11, 2013 at 1:12 AM, Benoît Bryon notifications@github.comwrote:

> Enabled Travis-CI for this fork:
> https://travis-ci.org/benoitbryon/docs.writethedocs/builds
> => it works :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/writethedocs/docs/pull/11#issuecomment-13372581..

## 

Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Pull request merged**
