### PR TITLE
Fixes encoding error when building under Windows

### PR DESCRIPTION
**Pull request by kdschlosser**
@vwheeler63 

Here is the second go. Lets get this one tested and merged and then we can address other issues in another PR

----
📚 Documentation preview 📚: https://writethedocs-www--2222.org.readthedocs.build/

### CODE REVIEW

**Comment by vwheeler63** [comment]
Good morning, Kevin! ( @kdschlosser )

cc:  @plaindocs 

Okay, the YAML intake APPEARS nicely handled.  (I am assuming that all the YAML stuff is read in before the .RST files are read.)

What I know for sure is that Sphinx is starting without errors and getting 31% into the reading phase before hitting the "next thing".   Sam, I can attest this is safe to merge.  The change only impacts those on the Windows platform, and it is certainly an improvement.

Kevin, we're getting a
image

Are you acquainted with rebasing (it's a bit cleaner than merging `main` back into `fix_emncoding_error`)?  I will assume you are, but in case you're not (I will assume that `https://github.com/kdschlosser/www` from the viewpoint of your local workstation is called `origin`):

1. Sync `https://github.com/kdschlosser/www` with this repo if not already done.
2. Then on your workstation:  `$ git fetch origin --all`  to fetch the updates to `main` branch.
3. `$ git checkout main`  to prepare to merge updates into your local `main` branch.
4. `$ git merge origin/main`  to sync your `main` branch to with `kdschlosser/www`.
5. `$ git checkout fix_emncoding_error` to prepare to rebase.
6. `$ git rebase --onto main`
7. Then finally, `$ git push origin fix_emncoding_error --force`.

That will handle the conflict and re-trigger the checks.

**Review by vwheeler63 — APPROVED** [review]

**Comment by vwheeler63** [comment]
@plaindocs Over to you, sir....  I can confirm that without the above code, the build only gets 14% of the way through and then generates this error:
```
Encoding error:
'charmap' codec can't decode byte 0x9d in position 7746: character maps to <undefined>
The full traceback has been saved in R:\TMPDIR\sphinx-err-q5w1xq87.log, if you want to report the issue to the developers.
```
And WITH the new code, it gets 31% of the way through the build (i.e. past the above error) and stops due to a different reason, which I am hoping to solve next (possibly with Kevin's help).

Kind regards,
Vic

**Review by plaindocs — APPROVED** [review]
Thanks for working on this folks! This looks fine to me. 

If we can get things working it looks like I might be able to add a Windows GitHub action build which will help keep it running.

**Comment by vwheeler63** [comment]
@kdschlosser Hi, Kevin.  Sam approved auto-merge, so it will happen as soon as the "out-of-date" situation is handled.

**Comment by kdschlosser** [comment]
onto the next bump in the road.... we will get it up and running no worries there... I can write the CI for Windows as well if ya want...

**Comment by plaindocs** [comment]
You're a star. I think #2226 mostly does the thing, but if there is anything to improve please point it out.

**Comment by kdschlosser** [comment]
I'll take a look at the code for #2226 and see if there is anything that needs to be done with it. Github actions is really easy to use and you don't have an overly complex build system or crazy amounts of build requirements so it should be fairly straight forward to add the Windows build to the CI.

**Pull request merged**
