### PR TITLE
Update formatting australia-2024-sessions.yaml

### PR DESCRIPTION
**Pull request by flicstar**
Fixed the list items in the talks and added some extra paragraphs from pretalx.

----
📚 Documentation preview 📚: https://writethedocs-www--2248.org.readthedocs.build/

### CODE REVIEW

**Comment by flicstar** [comment]
Gosh darrnitt. I can't tell what's making this fail. I thought it was an errant colon at line 70 but no dice.

**Comment by swapnilogale** [comment]
> Gosh darrnitt. I can't tell what's making this fail. I thought it was an errant colon at line 70 but no dice.

@flicstar, it's actually on Line 237, col 66, was a rogue (:) in the yaml - it's trying to looking for a key:value, which it is not. Replaced by (-)

**Comment by plaindocs** [comment]
Hey @flicstar , thanks for the edits! These changes will get blown away next time we run the sync with Pretalx (CC @swapnilogale )

**Comment by plaindocs** [comment]
If you do end up editing in Pretalx, a blank line before the bullet list will do the ul li dance, and it's a thing everyone misses.

**Review by plaindocs — APPROVED** [review]

**Pull request merged**
