### PR TITLE
Ugly output for run of show

### PR DESCRIPTION
**Pull request by plaindocs**
This copies and pastes into Spreadsheets.

### CODE REVIEW

**Comment by ericholscher** [comment]
I was thinking it would be good to make this data driven. Great minds 👍

**Comment by plaindocs** [comment]
Where should we put this? Just leave it as an unlinked page? @ericholscher @mxsasha

**Comment by mxsasha** [comment]
Yes, that makes sense. The content is not secret.

**Comment by mxsasha** [comment]
I need to make sure this still works in #1010.

**Comment by plaindocs** [comment]
@mxsasha @ericholscher wanna approve / merge

@thatdocslady the output in the preview should be pastable into a spreadsheet even before merging

**Review by mxsasha — APPROVED** [review]

**Pull request merged**
