### PR TITLE
MOAR link fixes

### PR DESCRIPTION
**Pull request by plaindocs**
So I got fed up of not being able to see if `/videos/index` was broken or not. 

So I tweaked the htmlProofer to

```diff
--- a/tox.ini
+++ b/tox.ini
@@ -45,4 +45,4 @@ commands_pre =
 
 commands =
     sphinx-build -b dirhtml -d {envtmpdir}/doctrees . {envtmpdir}/html
-    htmlproofer {envtmpdir}/html --alt-ignore '/.*/' --file-ignore "/2013/,/2014/,/2015/," --url-ignore '/2015/,/video/' --allow-hash-href
+    htmlproofer {envtmpdir}/html --alt-ignore '/.*/' --file-ignore "/2013/,/2014/,/2015/,/2016/,/blog/" --url-ignore '/2015/,/meetup/,/video/,/linkedin/,/jobs.writethedocs.org/' --allow-hash-href --internal-domains 'www.writethedocs.org' --disable-external
```

And did a bunch of fixes.

And we're down to 

```
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/conf/vilnius/2019/cfp/index.html
  *  internally linking to TBC, which does not exist (line 189)
     <a class="reference external" href="TBC">our CFP</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/search/index.html
  *  script is empty and has no src attribute (line 28)
```

The first is fixed in #817 
The second is irrelevant 

#835 fixed in 5aa330e

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
Lovely. 👍 We should enable the linkchecker as a failure once this is properly working.

**Comment by plaindocs** [comment]
So, with the passing build above, if we include `videos` back in the link check we get:

```
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/about/learning-resources/index.html
  *  internally linking to /videos/, which does not exist (line 73)
     <a class="reference external" href="/videos/">videos</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/conf/portland/2018/index.html
  *  internally linking to ../../../videos/portland/2018/, which does not exist (line 248)
     <a class="uk-button uk-button-secondary uk-text-center" href="../../../videos/portland/2018/">Watch the videos!</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/conf/portland/2018/news/thanks-recap/index.html
  *  internally linking to https://www.writethedocs.org/videos/portland/2018/, which does not exist (line 278)
     <a class="reference external" href="https://www.writethedocs.org/videos/portland/2018/">in our video
archive</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/conf/prague/2018/index.html
  *  internally linking to ../../../videos/prague/2018/, which does not exist (line 252)
     <a class="uk-button uk-button-secondary uk-text-center" href="../../../videos/prague/2018/">Watch the videos!</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/conf/prague/2018/news/thanks-recap/index.html
  *  internally linking to https://www.writethedocs.org/videos/prague/2018/, which does not exist (line 271)
     <a class="reference external" href="https://www.writethedocs.org/videos/prague/2018/">in our video archive</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/organizer-guide/meetups/starting/index.html
  *  internally linking to https://www.writethedocs.org/videos/, which does not exist (line 233)
     <a class="reference external" href="https://www.writethedocs.org/videos/">Write the Docs conferences</a>
- /home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/organizer-guide/meetups/sustainable-meetups/index.html
  *  internally linking to https://www.writethedocs.org/videos/, which does not exist (line 77)
     <a class="reference external" href="https://www.writethedocs.org/videos/">Write the Docs conferences</a>

```

And it seems to be more weirdness, because 

```
home/samuel/Nosync/Repositories/WTD/www/.tox/links/tmp/html/conf/portland/2018/index.html
  *  internally linking to ../../../videos/portland/2018/, which does not exist (line 248)
     <a class="uk-button uk-button-secondary uk-text-center" href="../../../videos/portland/2018/">Watch the videos!</a>
```

is working as far as I can tell. 

There *might* be a bug in the conditional exclusion code for `videos`? Leading to CI reporting broken links? :man_shrugging:

**Comment by plaindocs** [comment]
I AM EXCITE :tada:

**Comment by plaindocs** [comment]
OK, I think this is good to go. 

@ericholscher @mxsasha wanna give it any more :eyes: before we merge it in?

**Comment by ericholscher** [comment]
I'm happy to merge and iterate. I like the idea of slowly removing the excludes, but this is a huge win for now :)

**Comment by plaindocs** [comment]
Yeah, the main thing I want to do next is add `newsletter/` :-p but we do have some old content in there which we we'll need to curate. 

CC @bethaitman :trollface:

**Comment by bethaitman** [comment]
@plaindocs it's not totally obvious to me what I'd need to do to add `newsletter/` in, but if you let me know how then I'm v happy to go through and start fixing up broken links

**Pull request merged**
