### PR TITLE
Some maintenance with a view to less warnings

### PR DESCRIPTION
**Pull request by plaindocs**

### CODE REVIEW

**Comment by plaindocs** [comment]
@ericholscher no way of removing warnings about markdown files not in TOC right?

```
/home/samuel/Nosync/Repositories/WTD/www/docs/guide/contributing.md:: WARNING: document isn't included in any toctree
/home/samuel/Nosync/Repositories/WTD/www/docs/meetups/nyc.md:: WARNING: document isn't included in any toctree
/home/samuel/Nosync/Repositories/WTD/www/docs/meetups/philly.md:: WARNING: document isn't included in any toctree
```

Other than converting to rst and adding `:orphan:`

**Comment by ericholscher** [comment]
We should probably add them to a toctree :)

**Comment by plaindocs** [comment]
I thought you couldn't do that with the markdown files? But now you mention it that does seem like the obvious thing. On it.

**Comment by ericholscher** [comment]
We can inject RST into md -- https://raw.githubusercontent.com/writethedocs/www/master/docs/blog/newsletter-march-2017.md -- though we should probably just have a TOCTree at the top of the meetups dir, and include the subfiles.

**Pull request merged**
