### PR TITLE
Updates to support Windows builds

### PR DESCRIPTION
**Pull request by HeatherAtiFactor**
#220

### CODE REVIEW

**Comment by annegentle** [comment]
Yeah, Heather! Let me know if you want help with the merge conflict, happy to help you take this over the finish line. 🏃‍♀️

**Comment by plaindocs** [comment]
I put a `.bat` in with an unrelated commit yesterday, so also happy to help with the merge conflict.

**Comment by HeatherAtiFactor** [comment]
@plaindocs - I'm not sure how to compare our .bat files, but I think as long as the file is there, anyone with a Windows machine should be able to run the Sphinx commands. Is there anything else I should clean up on my end?

**Comment by ericholscher** [comment]
Thanks!

**Pull request merged**
