### PR TITLE
Updated Atlassian logo

### PR DESCRIPTION
**Pull request by swapnilogale**

### CODE REVIEW

**Comment by swapnilogale** [comment]
@plaindocs - fixing the logo for this year has broken a swag of files from last year. How do we fix this?

**Comment by plaindocs** [comment]
Hey @swapnilogale I'm not sure what you mean, can you be more specific?

**Comment by ericholscher** [comment]
Don't remove files, just add the new one.

**Comment by swapnilogale** [comment]
@plaindocs - can you approve this when you get a chance? Just updated the Atlassian logo for WTD AU conf.

**Review by plaindocs — APPROVED** [review]

**Pull request merged**
