### PR TITLE
Add job board to the site sidebar

### PR DESCRIPTION
**Pull request by ericholscher**
This also includes our upgraded deps PR

### CODE REVIEW

**Comment by mxsasha** [comment]
Why is #769 part of this PR again too? Because #772 fixed that already, so now it conflicts?

**Comment by ericholscher** [comment]
@mxsasha was just fixing it :)

**Review by plaindocs — COMMENTED** [review]
A++ great stuff.

BUT OMG that hanging button is too ugly to publish (am I channeling Mikey here?).

I looked at 

```
+                   .attr('class','toctree-l1')
```

but the first level li in the navbar doesn't have bullets.

We could move the line about the board to `l1` and make all of the jobs`l2` to mirror the nav display?

**Comment by ericholscher** [comment]
I futzed with the styles, we can remove the list style, but then it's hard to tell the listings apart.

**Comment by ericholscher** [comment]
@writethedocs/core Review please? Would like to get this shipped 👍

**Pull request merged**
