### PR TITLE
Fix meetup listings

### PR DESCRIPTION
**Pull request by bethaitman**
* Delete entries for meetup groups that no longer exist on meetup.com
* Correct links for broken meetup links

### CODE REVIEW

**Comment by plaindocs** [comment]
@bethaitman do you know if the Meetup.com get deleted as well?

**Comment by bethaitman** [comment]
@plaindocs This is basically me going through and deleting entries for groups that don't seem to exist on meetup.com anymore

**Comment by plaindocs** [comment]
Amazing! You are a star!

**Comment by plaindocs** [comment]
CC @mxsasha for future reference.

**Review by plaindocs — COMMENTED** [review]
LGTM

**Review by plaindocs — APPROVED** [review]
LGTM

**Pull request merged**
