### PR TITLE
Interview rachael stavchansky

### PR DESCRIPTION
**Pull request by Geodun**
adding interview with Rachael Stavchansky to hiring guide

### CODE REVIEW

**Comment by Geodun** [comment]
I've been using  this syntax for external links: [ .. _Python: http://www.python.org/ ]. But it doesn't work well with multiple words. Is there a better way to attach an external link to multiple words?

**Comment by Geodun** [comment]
Also, are content tags delimited by commas?

**Comment by ericholscher** [comment]
@Geodun https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#hyperlinks

**Comment by ericholscher** [comment]
We should keep tags as URL slugs, so lowercase and hypens in between words.

**Pull request merged**
