### PR TITLE
Update convince-your-manager.rst

### PR DESCRIPTION
**Pull request by KSalvione**
Added "testimonials" to the page.

### CODE REVIEW

**Comment by ericholscher** [comment]
Thanks for this update! 

Just wanted to know where this testimonial came from? Is there a public URL, or some other way to confirm it?

**Comment by firstladymb** [comment]
Hi @ericholscher! The testimonial came from this open issue via @erinkcochran87:
https://github.com/writethedocs/www/issues/419

I wasn't sure how to attach it to the open issue!

**Comment by ericholscher** [comment]
You should be able to include a link to the comment:

```

`Erin Cochran, Senior Technical Documentation Manager at Stitch <https://github.com/writethedocs/www/issues/419#issuecomment-364205174>`_

```

**Comment by firstladymb** [comment]
@KSalvione Do you want to try adding the link Eric mentioned? 

@ericholscher I also got a testimonial via Slack DM from one of our meetup attendees who also attended Write the Docs Portland 2017. Since it's not somewhere we can link to, would it be okay to link to her LinkedIn? It's a great quote!

"Write the Docs conferences are attended by people who are eager to share ideas and help each other improve. There's a lot of positive energy and excitement about what we do. In the Unconference sessions, I got answers to so many questions I had about tools, processes, best practices, and how to resolve tech writing pain points. After the conference, I changed the entire way my company produces customer-facing documentation, as well as the way we collaborate and share knowledge internally. Doc creation and updates are easier now, access to information has improved, and I got promoted for my efforts and dedication." -Jennifer Swallow, Senior Technical Writer at LogRhythm <https://www.linkedin.com/in/jenniferaswallow/>

**Comment by plaindocs** [comment]
You'd definitely want to check in with Jennifer Swallow before linking to her linkedin - maybe you already have?  :-) if so, sure.

**Comment by firstladymb** [comment]
@plaindocs Yes! I asked her how she wanted her name to appear and if we could link to her LinkedIn.  And good call on checking with people about linking to them; I was wondering about that in regard to the MeetUp organizers list. Thank you!

**Comment by KSalvione** [comment]
@firstladymb Yes, I apologize, I have been in school all day. I will take a look at that later tonight and add that link!

**Comment by ericholscher** [comment]
Would love to merge this with an update.

**Pull request closed without merging**
