### PR TITLE
Add organizer and other meta data to meetup listing page

### PR DESCRIPTION
**Pull request by agjohnson**
Organizer information is not complete and doesn't necessarily seem to match up
to Meetup data. We could automate this by hitting the Meetup API during build
and grabbing all of the organizer information.

Refs #54

### CODE REVIEW

**Comment by plaindocs** [comment]
Nice!

**Comment by plaindocs** [comment]
I'm gonna merge this in, and maybe @mjang wants to shout out in #meetup-organisers in case people wanna update or add their info.

@agjohnson Can you even get user data from the API? I thought maybe not. Or maybe you can just not the email.

**Comment by agjohnson** [comment]
It looks possible, but seems to require iterating over *all* members of the group.

https://secure.meetup.com/meetup_api/console/?path=/:urlname/members

Python query would be something like:

```python
organizers = [
    profile for profile in response
    if (
        profile['group_profile']['status'] == 'active' and
        profile['group_profile']['role'] == 'coorganizer'
    )
]
```

**Comment by mjang** [comment]
Thanks -- it's great to include organizer names! (But there are some updates that I'll try to PR this evening or maybe this weekend -- then I'll announce in #meetup-organizers)

**Pull request merged**
