### PR TITLE
Move to using Jinja includes instead of rst

### PR DESCRIPTION
**Pull request by ericholscher**
This allows us to use our Jinja variables in the include files

### CODE REVIEW

**Comment by plaindocs** [comment]
Looks great. Next steps, move data like sponsors, dates to the data file, and consolidate all of the templates.

Then templatize all of that data in the includes files for CFP, Writing Day, etc.

**Comment by plaindocs** [comment]
And we can probably just IF pre 2019 and IF 2019 so as not to back port?

**Comment by ericholscher** [comment]
Yea we should be able to not backport. I think we also need to think more deeply about our YAML structure before we do a full refactor here too. I want to figure out a better structure for the dates/schedule data.

**Comment by plaindocs** [comment]
Agree. But I don't think the two things are tightly connected.

**Comment by ericholscher** [comment]
Well, the way we structure the schedule & front page does rely heavily on that data, but agreed the other pages should be safe.

**Comment by plaindocs** [comment]
Dates being easily reusable *and* human readable / editable is a tough combo.

**Comment by plaindocs** [comment]
So we tried something like: 

```
date:
  year: 2019
  month: May
  day_1
    dom: 19
    main_event: {{ social }}
  day_ 2
...
```

right? And if instead of saying `do day1 day2 day3` which leads to exceptions for two and one day events we iterated over available days like


```
date:
  year: 2019
  month: May
  day
    - dom: 19
    main_event: {{ social }}
  day_ 2
    - dom: 20    
...
```

Either specifying a day of the week for each day, or specifying what day it starts on?

**Comment by ericholscher** [comment]
I'm thinking something like:

```
days:
   - - dotw: Saturday
     - month: May
     - day: 18
     - summary: Foo summary
  -  - dotw: Sunday
      - month: May
```

So that we can iterate over it, and not have like "day_three" which breaks for AU, etc.

**Comment by plaindocs** [comment]
Works for me.

**Review by plaindocs — APPROVED** [review]
Looks good.

**Comment by plaindocs** [comment]
Shall we merge as is and tackle YAML stuff separately?

**Comment by ericholscher** [comment]
Sure. 💯

**Pull request merged**
