### PR TITLE
Get a basic rendering of the 2017 NA speakers

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by plaindocs** [comment]
Does that build ok for you?

**Comment by ericholscher** [comment]
Ha, thanks for fixing :) I was poking it late last night, and was gonna fix it in the morning.

Builds well for me -- there's some HTML rendering issues, but thats on the list to fix today.

**Comment by plaindocs** [comment]
OK, so I think we need to add the 2017 speakers to `conf.py` and `transform_speakers` to get the `img_file` stuff. 

```
-for list_o_speakers in [na_speakers, eu_speakers]:
+na_2017_speakers = load_json('_data/2017-na-speakers.json')
+
+for list_o_speakers in [na_speakers, eu_speakers, na_2017_speakers]:
```

**Comment by plaindocs** [comment]
But that still doesn't work - so I'm missing something.

**Comment by plaindocs** [comment]
Also the speaker json was not split on the dual speaker like last year (see 61c8f2b where I split the json).

**Comment by ericholscher** [comment]
Yea, I can futz with the JSON more -- I like the datatemplate approach, but it does make it trickier to adapt the JSON based on the existing file metadata.

**Comment by plaindocs** [comment]
@ericholscher are you ok to fix this up if I just keep pushing bios / handles and pics into the branch?

**Comment by ericholscher** [comment]
Yep. Sorry, today got away from me, but I can get it rendering properly if we have all the data.

**Comment by plaindocs** [comment]
[EDIT] ignore previous error - newer version of sphinx - doh. 

Yes, looks great. :-) Now I can actually see it I can see if we need html/markdown as well.

**Comment by plaindocs** [comment]
Also - do we want html or markdown for the abstracts in the end?

**Comment by plaindocs** [comment]
I used this to one step encode / convert / remove line breaks
Next time I'd add back a line break for the h1
But hopefully we can remove the need for this kind of monkeying around for EU.

```
#!/bin/bash

for f in *.md; do
  cat $f | node_modules/.bin/he --encode | pandoc | tr -d '\n' > $f'.out'
done 
```

**Comment by plaindocs** [comment]
Some html nastiness in the CSS:

* `<li><p>` displays without bullet
* `<li>` without displays in tiny font

**Comment by ericholscher** [comment]
Gonna go ahead and merge this, as I believe I fixed most of the display issues.

**Pull request merged**
