### PR TITLE
Build fancy 404 pages

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by ericholscher** [comment]
Testing this in prod 🎉

**Comment by plaindocs** [comment]
Path issues in the fancy 404 page according to Travis CI.

**Comment by ericholscher** [comment]
Yea, the extension is broken currently for single version docs. Hrmph.

**Comment by humitos** [comment]
This PR https://github.com/rtfd/sphinx-notfound-page/pull/13 will add a config that will allow to use this extension with your site.

I'd appreciate if you can test it as well. Changing the dependency to point to the git branch and set `notfound_gh_pages=True` (the name will change before merge it), should be enough.

**Comment by plaindocs** [comment]
Hey @humitos thanks for pointing that out. 

What exactly are you suggesting I use in https://github.com/writethedocs/www/blob/notfound/requirements.txt#L17 ? I'm not really familiar with that format and am getting an 'archive format' error.

**Comment by humitos** [comment]
@plaindocs yeah, it's a weird way to specify a requirements for pip to use a branch instead of release version.

(the PR was merged, so no need to use that specific branch anymore, but `master` instead)

So, you can now change that line to,

    git+https://github.com/rtfd/sphinx-notfound-page@master#egg=sphinx-notfound-page

* `git+` tells pip to use git to install the dependency
* then the URL of the repository from where to get the source
* `@master` specifies the branch to use
* `#egg=` is the Python package name to use internally

More on the docs if you are interested and have plenty of time :) : https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by ericholscher** [comment]
We can just wait for the next release I think 👍

**Comment by ericholscher** [comment]
Ah, I saw you asked us to test it -- will do :)

**Comment by ericholscher** [comment]
:+1: -- https://deploy-preview-864--dentist-canary-64055.netlify.com/404/

**Comment by ericholscher** [comment]
Looks like the link checker doesn't like `/../foo/`, which is indeed a weird link :)

**Comment by plaindocs** [comment]
Thanks for the explanation @humitos , the `egg=` was tripping me up! 

@ericholscher would settting `notfound_no_urls_prefix` to `True` fix that?

**Comment by humitos** [comment]
Oh! I see the issue.

We are using `baseuri = '/'` but then we adds the relative link link `../foo/`.

This needs to be fixed in the extension.

In fact, it's weird that the browser handles this properly :)

**Comment by humitos** [comment]
This logic needs to be changed a little:

https://github.com/rtfd/sphinx-notfound-page/blob/86e4a959888ae263928b5d13335abfefe644ebfe/notfound/extension.py#L64-L70

Thanks for testing this ;)

**Comment by ericholscher** [comment]
I skipped the link check for now, and gonna merge this to make our 404's better 🎉

**Comment by humitos** [comment]
@plaindocs fancy 404 pages should work properly now. Example, https://www.writethedocs.org/not/found/url/

Read the Docs merged and deployed this PR: https://github.com/rtfd/readthedocs.org/pull/5754 that handle the case of `htmldir` builder (WTD's case).

Also, the linter should not fail anymore because of the weird links generated (fixed at https://github.com/rtfd/sphinx-notfound-page/pull/28)

Let me know if there are any other issue with this extension. Thanks!

**Comment by plaindocs** [comment]
Awesome! :tada: Thanks for looping back @humitos !

**Pull request merged**
