### PR TITLE
Add check for template and link names in each locale.

### PR DESCRIPTION
**Pull request by ericholscher**
Thoughts @plaindocs?

### CODE REVIEW

**Comment by plaindocs** [comment]
You're checking that we're not using `na` in `eu` and vice versa. Might be more sane to check for `na` in `na`? Ie, I added a `de` template in `eu` and the test passes.

**Comment by plaindocs** [comment]
Ignore the reference to #60 , mistaken link.

**Comment by ericholscher** [comment]
Yea -- it works for tito links and other stuff too this way. It's more about catching copypasta fouls than confirming correctness.

**Comment by ericholscher** [comment]
There's a bunch more we could be doing -- actual template linting/confirmation could probably be better done at the Sphinx level.

**Comment by plaindocs** [comment]
I will do research into the linter thing. But `time`.

**Pull request merged**
