### PR TITLE
Adding accessibility to style guide

### PR DESCRIPTION
**Pull request by alexandrascript**
Prompted by the year-end [newsletter](http://www.writethedocs.org/blog/write-the-docs-2018-stats/), I decided to make an addition to the style guide.

Happy to make further changes.

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
Looks great me to! Thanks!

**Comment by plaindocs** [comment]
Happy to merge this in as is, or for you to make more additions. :-)

**Comment by alexandrascript** [comment]
@plaindocs I'm sure I'll get back to it in the next week or two, as well as make additional changes. But for now, I say merge it :)

**Comment by ericholscher** [comment]
Thanks!

**Pull request merged**
