### PR TITLE
Add job fair page to website.

### PR DESCRIPTION
**Pull request by ericholscher**
Needs some more love.
The words aren't coming to me today.

### CODE REVIEW

**Comment by plaindocs** [comment]
Do you wanna split this out into Prospectus / Run of Show a little more, or shall I review and merge as is.

**Comment by ericholscher** [comment]
This is for attendees, not sponsors. It needs more love if you have marketing energy to throw at it :)

**Comment by plaindocs** [comment]
Meh, Netlify is 

```
4:35:10 PM:     Traceback (most recent call last):
4:35:10 PM:       File "<string>", line 1, in <module>
4:35:10 PM:       File "/tmp/pip-build-gO0GuR/tornado/setup.py", line 146, in <module>
4:35:10 PM:         raise ImportError("Tornado requires an up-to-date SSL module. This means "
4:35:10 PM:     ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
```

which I guess they might fix soon?

**Comment by plaindocs** [comment]
Otherwise I'm happy to merge this now and improve later (how often do we say that) ?

@ericholscher ?

**Comment by ericholscher** [comment]
Best to get it out, and make it better later I guess :)

**Pull request merged**
