### PR TITLE
Add initial Prague sponsors

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Review by plaindocs — APPROVED** [review]
Should these show on the sponsorpage as well as the index?

**Comment by thatdocslady** [comment]
Where is the media sponsor for Prague? Are we putting that separately?

**Comment by ericholscher** [comment]
@thatdocslady no sure about media sponsor, I don't have that on my sponsorship trello at all.

**Comment by ericholscher** [comment]
Media sponsor added and shipped 👍

**Pull request merged**
