### PR TITLE
Show speaker slides

### PR DESCRIPTION
**Pull request by plaindocs**
A pretty quick and dirty way of listing speaker slides on the conf page.

### CODE REVIEW

**Comment by plaindocs** [comment]
CC @mjang 

https://5cf91b0bc979c70007296d38--dentist-canary-64055.netlify.com/conf/portland/2019/#slides

**Comment by plaindocs** [comment]
Hmmm, putting the link in the global 'conf closed' thing isn't a great idea.

**Comment by ericholscher** [comment]
I feel like the slides should probably live with the video in the archive, not on the conference website. That way all the archives are together instead of spread across the websites.

**Comment by plaindocs** [comment]
I'd agree with that more if it was a talk archive not a video archive. :-p 

The other issue is that we only have a few slide links here and there. 

But yeah.

**Comment by plaindocs** [comment]
@ericholscher could I bug you to fix up https://github.com/writethedocs/www/pull/826 so I can change this PR to add the slides to the archive?

**Pull request closed without merging**
