### PR TITLE
WIP: integrated sphinxcontrib-spelling

### PR DESCRIPTION
**Pull request by sergeykolosov**
Things to consider:
* spelling word-list is pretty much empty yet;
* it may be worth using a separate tox environment for spelling (there are both pros and cons).

### CODE REVIEW

**Comment by plaindocs** [comment]
Cool stuff! Got a link to pros and cons of the separate environment? ;-)

**Comment by plaindocs** [comment]
Hey @mxsasha @ericholscher did you see this? Any thoughts on whether it is worth doing the initial work of populating the "correct words list"?

**Comment by plaindocs** [comment]
I'll find out what amount of words we're talking about here.

**Comment by plaindocs** [comment]
After kicking some deps I found

WARNING: Found 2864 misspelled words
build succeeded, 6 warnings.

Which then boils down to 660 words, mostly names and brands. 

[spelling-unique.txt](https://github.com/writethedocs/www/files/3376328/spelling-unique.txt)

Would be pretty straightforward  zoom through that list, and add it directly to the spelling file.

**Comment by plaindocs** [comment]
One could even easily script adding all speaker names to the list when adding a speaker YAML.

Plus some decent config option https://github.com/sphinx-contrib/spelling/blob/master/docs/source/customize.rst#word-filters

Overall I'm inclined to add this in. @mxsasha @sergeykolosov any more thoughts?

**Comment by mxsasha** [comment]
I think this is good! Maybe we shouldn't add all the misspelled current words though? I see a bunch of British spelling in there (this may have been me 😬).

**Comment by plaindocs** [comment]
I'll pick this up, add some  words (trying to avoid British spellings)

**Comment by plaindocs** [comment]
Replaced by #1554 

I ran into issues with `ablog`, and we're already using `vale` elsewhere. If we ever do switch back to this the word list is reusable anyway, and that is where most of the work is.

**Pull request closed without merging**
