### PR TITLE
Update vale checks take2

### PR DESCRIPTION
**Pull request by plaindocs**
Replaces #449

### CODE REVIEW

**Comment by plaindocs** [comment]
~So I think tox is doing something really weird, cos I'm getting different results for running vale locally, running vale in tox, locally and the tox running on travis ci...~

~Which is *really* unhelpful for what we're doing here.~

Gah, tox builds to no standard output dir in .tox

**Comment by ericholscher** [comment]
We should look at merging this. It looks useful :)

**Comment by ericholscher** [comment]
@plaindocs this still worth poking at? ^^

**Comment by plaindocs** [comment]
Yeah, it sadly isn't really now we're making almost everything use the variables. What might be more interesting is to ignore the *source* and lint the *output* html.

But to do that we'd have to configure sphinx to pass the vale "ignore this bit" comments though to the output, and it all gets pretty fiddly.

**Pull request closed without merging**
